# Generated by Django 4.1.5 on 2025-02-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0004_remove_projectproduct_client_type_and_more'),
        ('auto_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apipublic',
            name='client',
        ),
        migrations.CreateModel(
            name='ApiHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('key', models.CharField(max_length=128, verbose_name='键')),
                ('value', models.TextField(verbose_name='值')),
                ('status', models.SmallIntegerField(default=0, verbose_name='是否默认开启')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'api_headers',
                'ordering': ['-id'],
            },
        ),
    ]
