# Generated by Django 4.1.5 on 2025-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0002_remove_apipublic_client_apiheaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicase',
            name='front_headers',
            field=models.JSONField(null=True, verbose_name='前置请求头'),
        ),
        migrations.AlterField(
            model_name='apicasedetailed',
            name='header',
            field=models.JSONField(max_length=2048, null=True, verbose_name='请求头'),
        ),
    ]
