# Generated by Django 4.1.5 on 2025-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0002_remove_apicasedetailed_ass_response_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='error_retry',
            field=models.SmallIntegerField(null=True, verbose_name='失败重试'),
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='retry_interval',
            field=models.SmallIntegerField(null=True, verbose_name='重试间隔'),
        ),
    ]
