# Generated by Django 4.1.5 on 2025-07-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0003_apicasedetailedparameter_error_retry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicasedetailedparameter',
            old_name='header',
            new_name='headers',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='header',
            new_name='headers',
        ),
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='data',
            field=models.TextField(null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='file',
            field=models.TextField(null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='front_func',
            field=models.TextField(null=True, verbose_name='前置自定义函数'),
        ),
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='json',
            field=models.TextField(null=True, verbose_name='json'),
        ),
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='params',
            field=models.TextField(null=True, verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='data',
            field=models.TextField(null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='file',
            field=models.TextField(null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='json',
            field=models.TextField(null=True, verbose_name='json'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='params',
            field=models.TextField(null=True, verbose_name='参数'),
        ),
    ]
