# Generated by Django 4.1.5 on 2025-02-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0001_initial'),
        ('auto_system', '0004_remove_projectproduct_client_type_and_more'),
        ('auto_api', '0003_alter_apicase_front_headers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCaseSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='测试套件名称')),
                ('case_flow', models.TextField(null=True, verbose_name='步骤顺序')),
                ('parametrize', models.JSONField(null=True, verbose_name='参数化')),
                ('status', models.SmallIntegerField(default=2, verbose_name='状态')),
                ('front_custom', models.JSONField(null=True, verbose_name='前置自定义')),
                ('front_sql', models.JSONField(null=True, verbose_name='前置sql')),
                ('posterior_sql', models.JSONField(null=True, verbose_name='后置sql')),
                ('case_people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user', verbose_name='测试套件责任人')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.productmodule')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'api_case_suite',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApiCaseSuiteDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('case_sort', models.IntegerField(null=True, verbose_name='用例排序')),
                ('status', models.SmallIntegerField(default=2, verbose_name='状态')),
                ('result_data', models.JSONField(null=True, verbose_name='最近一次执行结果')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicase')),
                ('case_suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicasesuite')),
            ],
            options={
                'db_table': 'api_case_suite_detailed',
            },
        ),
    ]
