# Generated by Django 4.1.5 on 2025-07-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0004_rename_header_apicasedetailedparameter_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='file',
            field=models.JSONField(null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='file',
            field=models.JSONField(null=True, verbose_name='file'),
        ),
    ]
