# Generated by Django 4.1.5 on 2025-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0004_apicasesuite_apicasesuitedetailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiinfo',
            name='front_custom',
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='front_json_path',
            field=models.JSONField(null=True, verbose_name='后置jsonpath提取'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='front_re',
            field=models.JSONField(null=True, verbose_name='后置正则提取'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='result_data',
            field=models.JSONField(null=True, verbose_name='最近一次执行结果'),
        ),
    ]
