# Generated by Django 4.1.5 on 2025-02-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0005_remove_apiinfo_front_custom_apiinfo_front_json_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='ass_response_value',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='ass_response_whole',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='ass_sql',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='data',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='file',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='front_sql',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='header',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='json',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='params',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='posterior_response',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='posterior_sleep',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='posterior_sql',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='status',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='url',
        ),
        migrations.AddField(
            model_name='apicasedetailed',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='测试用例名称'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApiCaseDetailedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('url', models.CharField(max_length=1024, null=True, verbose_name='请求url')),
                ('header', models.JSONField(max_length=2048, null=True, verbose_name='请求头')),
                ('params', models.JSONField(null=True, verbose_name='参数')),
                ('data', models.JSONField(null=True, verbose_name='data')),
                ('json', models.JSONField(null=True, verbose_name='json')),
                ('file', models.JSONField(null=True, verbose_name='file')),
                ('front_sql', models.JSONField(null=True, verbose_name='前置sql')),
                ('ass_sql', models.JSONField(null=True, verbose_name='sql断言')),
                ('ass_response_whole', models.JSONField(null=True, verbose_name='响应全匹配断言')),
                ('ass_response_value', models.JSONField(null=True, verbose_name='响应值断言')),
                ('posterior_sql', models.JSONField(null=True, verbose_name='后置sql')),
                ('posterior_response', models.JSONField(null=True, verbose_name='后置响应处理')),
                ('posterior_sleep', models.CharField(max_length=64, null=True, verbose_name='步骤顺序')),
                ('status', models.SmallIntegerField(default=2, verbose_name='状态')),
                ('result_data', models.JSONField(null=True, verbose_name='最近一次执行结果')),
                ('case_detailed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicasedetailed')),
            ],
            options={
                'db_table': 'api_case_detailed_parameter',
            },
        ),
    ]
