# Generated by Django 4.1.5 on 2025-07-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0005_alter_apicasedetailedparameter_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='ass_general',
            field=models.JSONField(default=list, verbose_name='sql断言'),
        ),
    ]
