# Generated by Django 4.1.5 on 2025-02-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0006_remove_apicasedetailed_ass_response_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailed',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
    ]
