# Generated by Django 4.1.5 on 2025-07-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0009_testsuitedetails_parametrize'),
        ('auto_api', '0007_apicasedetailedparameter_is_case_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailed',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct'),
            preserve_default=False,
        ),
    ]
