# Generated by Django 4.1.5 on 2025-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0007_apicasedetailed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='name',
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='步骤名称'),
            preserve_default=False,
        ),
    ]
