# Generated by Django 4.1.5 on 2025-02-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0008_remove_apicasedetailed_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasedetailedparameter',
            name='url',
        ),
    ]
