# Generated by Django 4.1.5 on 2025-02-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0009_remove_apicasedetailedparameter_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiinfo',
            old_name='front_json_path',
            new_name='posterior_json_path',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='front_re',
            new_name='posterior_re',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='front_custom',
        ),
        migrations.RemoveField(
            model_name='apicasedetailedparameter',
            name='ass_response_value',
        ),
        migrations.RemoveField(
            model_name='apicasedetailedparameter',
            name='ass_response_whole',
        ),
        migrations.AddField(
            model_name='apicase',
            name='front_func',
            field=models.JSONField(null=True, verbose_name='前置方法'),
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='ass_json_all',
            field=models.JSONField(null=True, verbose_name='响应JSON全匹配断言'),
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='ass_jsonpath',
            field=models.JSONField(null=True, verbose_name='响应jsonpath断言'),
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='ass_text_all',
            field=models.JSONField(null=True, verbose_name='响应文本全匹配断言'),
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='front_func',
            field=models.TextField(null=True, verbose_name='后置自定义'),
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='posterior_custom',
            field=models.TextField(null=True, verbose_name='后置自定义'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='posterior_custom',
            field=models.TextField(null=True, verbose_name='后置自定义'),
        ),
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='posterior_sleep',
            field=models.CharField(max_length=64, null=True, verbose_name='强制等待'),
        ),
    ]
