# Generated by Django 4.1.5 on 2026-03-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0009_apicasedetailedparameter_posterior_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='ass_schema',
            field=models.JSONField(null=True, verbose_name='schema配置'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='ass_schema',
            field=models.JSONField(null=True, verbose_name='schema配置'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='is_schema',
            field=models.SmallIntegerField(default=0, verbose_name='schema状态，是否给这个接口全用例开启'),
        ),
    ]
