# Generated by Django 4.1.5 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0010_apicasedetailedparameter_ass_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasedetailedparameter',
            name='ass_schema',
        ),
        migrations.RemoveField(
            model_name='apicasedetailedparameter',
            name='posterior_response_text',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='ass_schema',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='is_schema',
        ),
        migrations.AlterField(
            model_name='apicase',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apicasedetailed',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apicasedetailedparameter',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apiheaders',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='是否默认开启'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='type',
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name='接口的类型'),
        ),
        migrations.AlterField(
            model_name='apipublic',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apipublic',
            name='type',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='自定义变量类型'),
        ),
    ]
