# Generated by Django 4.1.5 on 2025-02-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0010_rename_front_json_path_apiinfo_posterior_json_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicasedetailedparameter',
            old_name='posterior_custom',
            new_name='posterior_func',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='posterior_custom',
            new_name='posterior_func',
        ),
    ]
