# Generated by Django 4.1.5 on 2026-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0011_remove_apicasedetailedparameter_ass_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='posterior_response_text',
            field=models.JSONField(default=list, verbose_name='后置响应文本处理'),
        ),
    ]
