# Generated by Django 4.1.5 on 2025-02-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0011_rename_posterior_custom_apicasedetailedparameter_posterior_func_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicase',
            old_name='front_func',
            new_name='front_custom',
        ),
    ]
