# Generated by Django 4.1.5 on 2025-02-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0012_rename_front_func_apicase_front_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasesuite',
            name='case_flow',
        ),
        migrations.RemoveField(
            model_name='apicasesuite',
            name='front_custom',
        ),
        migrations.RemoveField(
            model_name='apicasesuite',
            name='front_sql',
        ),
        migrations.RemoveField(
            model_name='apicasesuite',
            name='posterior_sql',
        ),
        migrations.AddField(
            model_name='apicasesuite',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicase'),
        ),
        migrations.AddField(
            model_name='apicasesuite',
            name='result_data',
            field=models.JSONField(null=True, verbose_name='最近一次执行结果'),
        ),
        migrations.DeleteModel(
            name='ApiCaseSuiteDetailed',
        ),
    ]
