# Generated by Codex on 2026-05-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0002_remove_unused_entity_fields'),
        ('auto_api', '0012_apicasedetailedparameter_ass_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCaseDataFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='配置名称')),
                ('stage', models.SmallIntegerField(default=1, verbose_name='执行阶段')),
                ('sort', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('alias', models.CharField(blank=True, max_length=64, null=True, verbose_name='上下文别名')),
                ('field_overrides', models.JSONField(default=dict, verbose_name='字段覆盖')),
                ('output_mapping', models.JSONField(default=list, verbose_name='输出映射')),
                ('cleanup_strategy', models.SmallIntegerField(blank=True, null=True, verbose_name='清理策略覆盖')),
                ('status', models.SmallIntegerField(db_index=True, default=1, verbose_name='状态')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_api.apicase')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_data_factory.datafactorytemplate')),
            ],
            options={
                'db_table': 'api_case_data_factory',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
