# Generated by Django 4.1.5 on 2026-05-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0018_alter_projectproduct_name_and_more'),
        ('auto_api', '0014_apicase_scenario_description_apicase_scenario_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('test_env', models.SmallIntegerField(blank=True, choices=[(0, '测试环境'), (1, '预发环境'), (2, '生产环境'), (3, '开发环境'), (4, '验收环境'), (5, '仿真环境')], default=None, null=True, verbose_name='测试环境')),
                ('name', models.CharField(max_length=64, verbose_name='授权名称')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], db_index=True, default=1, verbose_name='状态')),
                ('auth_type', models.SmallIntegerField(choices=[(0, '接口登录'), (1, '自定义代码')], db_index=True, default=0, verbose_name='授权方式')),
                ('custom_code', models.TextField(blank=True, null=True, verbose_name='自定义授权代码')),
                ('cache_keys', models.JSONField(default=list, verbose_name='缓存变量名')),
                ('cache_data', models.JSONField(default=dict, verbose_name='授权缓存数据')),
                ('token_ttl', models.IntegerField(default=1440, verbose_name='Token有效期(分钟)')),
                ('refresh_margin', models.IntegerField(default=5, verbose_name='提前刷新时间(分钟)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='最近刷新时间')),
                ('last_refresh_status', models.SmallIntegerField(choices=[(0, '未刷新'), (1, '刷新成功'), (2, '刷新失败')], default=0, verbose_name='最近刷新状态')),
                ('last_refresh_error', models.TextField(blank=True, null=True, verbose_name='最近刷新错误')),
                ('refresh_mode', models.SmallIntegerField(choices=[(0, '执行时检测刷新'), (1, '定时刷新'), (2, '执行时检测+定时刷新')], db_index=True, default=0, verbose_name='刷新方式')),
                ('refreshing', models.BooleanField(default=False, verbose_name='是否刷新中')),
                ('refresh_lock_until', models.DateTimeField(blank=True, null=True, verbose_name='刷新锁过期时间')),
                ('api_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apiinfo', verbose_name='登录接口')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
                ('time_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.timetasks', verbose_name='定时策略')),
            ],
            options={
                'db_table': 'api_auth_config',
                'ordering': ['-id'],
                'unique_together': {('project_product', 'test_env', 'name')},
            },
        ),
    ]
