# Generated by Django 4.1.5 on 2023-11-13 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0001_initial'),
        ('auto_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCaseDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('case_sort', models.IntegerField(null=True, verbose_name='用例排序')),
                ('header', models.JSONField(max_length=2048, null=True, verbose_name='请求头')),
                ('params', models.JSONField(null=True, verbose_name='参数')),
                ('data', models.TextField(null=True, verbose_name='data')),
                ('json', models.JSONField(null=True, verbose_name='json')),
                ('ass', models.JSONField(null=True, verbose_name='公共断言')),
            ],
            options={
                'db_table': 'api_case_detailed',
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('type', models.SmallIntegerField(verbose_name='接口的类型')),
                ('name', models.CharField(max_length=64, verbose_name='接口名称')),
                ('client', models.SmallIntegerField(verbose_name='什么端')),
                ('url', models.CharField(max_length=1024, verbose_name='请求url')),
                ('method', models.SmallIntegerField(verbose_name='请求方法')),
                ('header', models.JSONField(max_length=2048, null=True, verbose_name='请求头')),
                ('params', models.JSONField(null=True, verbose_name='参数')),
                ('data', models.TextField(null=True, verbose_name='data')),
                ('json', models.JSONField(null=True, verbose_name='json')),
                ('ass', models.JSONField(null=True, verbose_name='公共断言')),
                ('status', models.SmallIntegerField(null=True, verbose_name='状态')),
                ('module_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='auto_user.projectmodule')),
                ('project',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project')),
            ],
            options={
                'db_table': 'api_info',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='apicasegroup',
            name='project',
        ),
        migrations.RemoveField(
            model_name='apicasegroup',
            name='time_name',
        ),
        migrations.RemoveField(
            model_name='apiresult',
            name='case',
        ),
        migrations.RemoveField(
            model_name='apiresult',
            name='case_group',
        ),
        migrations.RemoveField(
            model_name='apiresult',
            name='project',
        ),
        migrations.RemoveField(
            model_name='apiresult',
            name='test_obj',
        ),
        migrations.RenameField(
            model_name='apicase',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='apipublic',
            old_name='state',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='ass',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='body',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='client',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='header',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='method',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='rely',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='type',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='url',
        ),
        migrations.AddField(
            model_name='apicase',
            name='case_flow',
            field=models.CharField(max_length=2000, null=True, verbose_name='步骤顺序'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='case_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user',
                                    verbose_name='用例责任人'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='name',
            field=models.CharField(max_length=64, verbose_name='测试用例名称'),
        ),
        migrations.DeleteModel(
            name='ApiAssertions',
        ),
        migrations.DeleteModel(
            name='ApiCaseGroup',
        ),
        migrations.DeleteModel(
            name='ApiResult',
        ),
        migrations.AddField(
            model_name='apicasedetailed',
            name='api_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apiinfo'),
        ),
        migrations.AddField(
            model_name='apicasedetailed',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicase'),
        ),
    ]
