# Generated by Django 4.1.5 on 2024-05-12 00:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicase',
            old_name='module_name',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='module_name',
            new_name='module',
        ),
    ]
