# Generated by Django 4.1.5 on 2024-11-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicase',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apicasedetailed',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apipublic',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状态'),
        ),
    ]
