# Generated by Django 4.1.5 on 2023-03-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0005_alter_timetasks_name'),
        ('auto_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasegroup',
            name='fail',
        ),
        migrations.RemoveField(
            model_name='apicasegroup',
            name='res',
        ),
        migrations.AddField(
            model_name='apicasegroup',
            name='time_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.timetasks', to_field='name'),
        ),
    ]
