# Generated by Django 4.1.5 on 2024-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0002_remove_apiinfo_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='front_headers',
            field=models.TextField(null=True, verbose_name='前置请求头'),
        ),
    ]
