# Generated by Django 4.1.5 on 2024-11-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0002_alter_apicase_status_alter_apicasedetailed_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='type',
            field=models.SmallIntegerField(default=1, verbose_name='接口的类型'),
        ),
    ]
