# Generated by Django 4.1.5 on 2023-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0003_remove_apicasedetailed_ass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicasedetailed',
            name='ass_response_whole',
            field=models.TextField(null=True, verbose_name='响应全匹配断言'),
        ),
    ]
