# Generated by Django 4.1.5 on 2024-11-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0003_apicase_front_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicasedetailed',
            name='ass_response_whole',
            field=models.JSONField(null=True, verbose_name='响应全匹配断言'),
        ),
    ]
