# Generated by Django 4.1.5 on 2023-12-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0004_alter_apicasedetailed_ass_response_whole'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='file',
            field=models.CharField(max_length=2048, null=True, verbose_name='文件'),
        ),
    ]
