# Generated by Django 4.1.5 on 2023-12-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0006_remove_apiinfo_ass_alter_apiinfo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicasedetailed',
            name='header',
            field=models.TextField(max_length=2048, null=True, verbose_name='请求头'),
        ),
    ]
