# Generated by Django 4.1.5 on 2023-12-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0007_alter_apicasedetailed_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('test_suite_id', models.BigIntegerField(null=True, verbose_name='测试套件id')),
                ('headers', models.JSONField(max_length=2048, null=True, verbose_name='请求头')),
                ('params', models.JSONField(null=True, verbose_name='参数')),
                ('data', models.JSONField(null=True, verbose_name='data')),
                ('json', models.JSONField(null=True, verbose_name='json')),
                ('file', models.CharField(max_length=2048, null=True, verbose_name='文件')),
                ('response_code', models.CharField(max_length=64, null=True, verbose_name='响应code码')),
                ('response_time', models.CharField(max_length=64, null=True, verbose_name='响应时间')),
                ('response_headers', models.JSONField(null=True, verbose_name='响应headers')),
                ('response_text', models.TextField(null=True, verbose_name='响应文本')),
                ('response_json', models.JSONField(null=True, verbose_name='响应文本json对象')),
                ('status', models.SmallIntegerField(null=True, verbose_name='断言结果')),
            ],
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='response_headers',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='response_text',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='response_time',
        ),
        migrations.AlterField(
            model_name='apicasedetailed',
            name='data',
            field=models.JSONField(null=True, verbose_name='data'),
        ),
    ]
