# Generated by Django 4.1.5 on 2023-12-14 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0008_apiresult_remove_apicasedetailed_response_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiresult',
            name='api_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apiinfo'),
        ),
        migrations.AddField(
            model_name='apiresult',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicase'),
        ),
    ]
