# Generated by Django 4.1.5 on 2023-12-14 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0009_apiresult_api_info_apiresult_case'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apiresult',
            table='api_result',
        ),
    ]
