# Generated by Django 4.1.5 on 2023-12-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0010_alter_apiresult_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailed',
            name='url',
            field=models.CharField(max_length=1024, null=True, verbose_name='请求url'),
        ),
        migrations.AddField(
            model_name='apiresult',
            name='url',
            field=models.CharField(max_length=1024, null=True, verbose_name='请求url'),
        ),
    ]
