# Generated by Django 4.1.5 on 2023-12-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0011_apicasedetailed_url_apiresult_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresult',
            name='data',
            field=models.TextField(null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='headers',
            field=models.TextField(null=True, verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='json',
            field=models.TextField(null=True, verbose_name='json'),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='params',
            field=models.TextField(null=True, verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='response_headers',
            field=models.TextField(null=True, verbose_name='响应headers'),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='response_json',
            field=models.TextField(null=True, verbose_name='响应文本json对象'),
        ),
    ]
