# Generated by Django 4.1.5 on 2023-12-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0012_alter_apiresult_data_alter_apiresult_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiresult',
            name='case_detailed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='auto_api.apicasedetailed'),
        ),
    ]
