# Generated by Django 4.1.5 on 2023-12-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0013_apiresult_case_detailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicasedetailed',
            name='file',
            field=models.JSONField(null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='file',
            field=models.JSONField(null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='file',
            field=models.TextField(null=True, verbose_name='file'),
        ),
    ]
