# Generated by Django 4.1.5 on 2023-12-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0006_project_screenshot_folder_project_upload_folder'),
        ('auto_api', '0014_alter_apicasedetailed_file_alter_apiinfo_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='module_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='auto_user.projectmodule'),
        ),
    ]
