# Generated by Django 4.1.5 on 2023-12-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0016_apiresult_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiresult',
            name='all_cache',
            field=models.TextField(null=True, verbose_name='执行到这个用例时的缓存数据'),
        ),
    ]
