# Generated by Django 4.1.5 on 2023-12-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0017_apiresult_all_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailed',
            name='posterior_sleep',
            field=models.CharField(max_length=64, null=True, verbose_name='步骤顺序'),
        ),
    ]
