# Generated by Django 4.1.5 on 2024-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0018_apicasedetailed_posterior_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='接口名称'),
        ),
    ]
