# Generated by Django 4.1.5 on 2024-01-24 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0019_alter_apiinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('test_suite_id', models.BigIntegerField(null=True, verbose_name='测试套件id')),
                ('status', models.SmallIntegerField(null=True, verbose_name='断言结果')),
                ('error_message', models.CharField(max_length=1024, null=True, verbose_name='失败原因')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicase')),
            ],
            options={
                'db_table': 'api_case_result',
            },
        ),
        migrations.CreateModel(
            name='ApiInfoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('test_suite_id', models.BigIntegerField(null=True, verbose_name='测试套件id')),
                ('url', models.TextField(null=True, verbose_name='请求url')),
                ('headers', models.TextField(null=True, verbose_name='请求头')),
                ('params', models.TextField(null=True, verbose_name='参数')),
                ('data', models.TextField(null=True, verbose_name='data')),
                ('json', models.TextField(null=True, verbose_name='json')),
                ('file', models.TextField(null=True, verbose_name='file')),
                ('response_code', models.CharField(max_length=64, null=True, verbose_name='响应code码')),
                ('response_time', models.CharField(max_length=64, null=True, verbose_name='响应时间')),
                ('response_headers', models.TextField(null=True, verbose_name='响应headers')),
                ('response_text', models.TextField(null=True, verbose_name='响应文本')),
                ('response_json', models.TextField(null=True, verbose_name='响应文本json对象')),
                ('status', models.SmallIntegerField(null=True, verbose_name='断言结果')),
                ('error_message', models.CharField(max_length=1024, null=True, verbose_name='失败原因')),
                ('all_cache', models.TextField(null=True, verbose_name='执行到这个用例时的缓存数据')),
                ('assertion', models.TextField(null=True, verbose_name='断言')),
                ('api_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apiinfo')),
                ('case_detailed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicasedetailed')),
            ],
            options={
                'db_table': 'api_info_result',
            },
        ),
        migrations.DeleteModel(
            name='ApiResult',
        ),
    ]
