# Generated by Django 4.1.5 on 2024-02-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0022_apiinforesult_case_apiinforesult_case_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='level',
            field=models.SmallIntegerField(null=True, verbose_name='用例级别'),
        ),
    ]
