# Generated by Django 4.1.5 on 2024-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0023_apicase_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apipublic',
            name='public_type',
        ),
        migrations.AlterField(
            model_name='apipublic',
            name='type',
            field=models.SmallIntegerField(null=True, verbose_name='自定义变量类型'),
        ),
    ]
