# Generated by Django 4.1.5 on 2024-02-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_api', '0024_remove_apipublic_public_type_alter_apipublic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='front_custom',
            field=models.JSONField(null=True, verbose_name='前置自定义'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='front_sql',
            field=models.JSONField(null=True, verbose_name='前置sql'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='posterior_sql',
            field=models.JSONField(null=True, verbose_name='后置sql'),
        ),
    ]
