# Generated by Django 4.1.5 on 2024-04-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0025_apicase_front_custom_apicase_front_sql_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailed',
            name='status',
            field=models.SmallIntegerField(null=True, verbose_name='状态'),
        ),
    ]
