# Generated by Django 5.0.3 on 2024-04-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0025_apicase_front_custom_apicase_front_sql_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('type', models.SmallIntegerField(verbose_name='参数类型')),
                ('key', models.CharField(max_length=1024, verbose_name='参数的key')),
                ('value', models.TextField(null=True, verbose_name='参数的value')),
                ('describe', models.CharField(max_length=1024, null=True, verbose_name='参数的key')),
                ('api_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apiinfo')),
            ],
            options={
                'db_table': 'api_info_details',
            },
        ),
    ]
