# Generated by Django 5.0.3 on 2024-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0025_apicase_front_custom_apicase_front_sql_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='dump_data',
        ),
    ]
