# Generated by Django 4.1.5 on 2024-04-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0026_remove_apicasedetailed_dump_data_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='apicasedetailed',
        #     name='dump_data',
        # ),
    ]
