# Generated by Django 5.0.3 on 2024-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0026_apiinfodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='parameter',
            field=models.JSONField(null=True, verbose_name='参数的listID'),
        ),
    ]
