# Generated by Django 5.0.3 on 2024-04-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0027_apiinfo_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='dump_data',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='parameter',
        ),
    ]
