# Generated by Django 5.0.3 on 2024-04-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0028_remove_apicasedetailed_dump_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiInfoDetails',
        ),
    ]
