# Generated by Django 4.1.5 on 2025-02-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0006_remove_projectproduct_auto_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.tasks'),
        ),
    ]
