# Generated by Django 4.1.5 on 2025-10-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0009_testsuitedetails_parametrize'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuitedetails',
            name='case_sum',
            field=models.SmallIntegerField(default=0, verbose_name='用例数'),
        ),
        migrations.AddField(
            model_name='testsuitedetails',
            name='fail',
            field=models.SmallIntegerField(default=0, verbose_name='失败数'),
        ),
        migrations.AddField(
            model_name='testsuitedetails',
            name='success',
            field=models.SmallIntegerField(default=0, verbose_name='成功数'),
        ),
        migrations.AddField(
            model_name='testsuitedetails',
            name='warning',
            field=models.SmallIntegerField(default=0, verbose_name='警告数'),
        ),
    ]
