# Generated by Django 4.1.5 on 2025-10-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0010_testsuitedetails_case_sum_testsuitedetails_fail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproduct',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='产品名称'),
        ),
    ]
