# Generated by Django 4.1.5 on 2025-12-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0013_filedata_project_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='fail_notice',
            field=models.SmallIntegerField(default=0, verbose_name='只有失败发送'),
        ),
    ]
