# Generated by Django 4.1.5 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0014_tasks_fail_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='is_notice',
            field=models.SmallIntegerField(db_index=True, verbose_name='是否发送通知'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='status',
            field=models.SmallIntegerField(db_index=True, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='testsuitedetails',
            name='status',
            field=models.SmallIntegerField(db_index=True, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='testsuitedetails',
            name='type',
            field=models.SmallIntegerField(db_index=True, verbose_name='类型'),
        ),
        migrations.AddIndex(
            model_name='testsuitedetails',
            index=models.Index(fields=['type', 'status'], name='idx_type_status'),
        ),
    ]
