# Generated by Django 4.1.5 on 2026-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0016_testsuitedetails_idx_suite_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='db_type',
            field=models.SmallIntegerField(default=0, verbose_name='数据库类型'),
        ),
    ]
