# Generated by Django 4.1.5 on 2026-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0017_database_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproduct',
            name='name',
            field=models.CharField(max_length=64, verbose_name='产品名称'),
        ),
        migrations.AlterUniqueTogether(
            name='projectproduct',
            unique_together={('project', 'name')},
        ),
    ]
