# Generated by Django 4.1.5 on 2026-06-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0018_alter_projectproduct_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteDetailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('result_data', models.JSONField(null=True, verbose_name='完整测试结果')),
                ('result_size', models.BigIntegerField(default=0, verbose_name='结果大小')),
                ('test_suite_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_payload', to='auto_system.testsuitedetails')),
            ],
            options={
                'db_table': 'test_suite_detail_result',
                'ordering': ['-create_time'],
            },
        ),
    ]
