# Generated by Django 4.1.5 on 2026-01-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_system', '0014_tasks_fail_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('script_content', models.TextField()),
                ('script_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('log_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '待执行'), (1, '运行中'), (2, '已停止'), (3, '失败'), (4, '已完成')], default=0, verbose_name='状态')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('is_notice', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], default=0, verbose_name='是否发送通知')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('notice_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.noticegroup', verbose_name='通知组')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'monitoring_task',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.SmallIntegerField(choices=[(0, '信息'), (1, '失败'), (2, '警告'), (3, '调试')], default=0, verbose_name='状态')),
                ('msg', models.TextField(blank=True, default=None, null=True, verbose_name='消息内容')),
                ('send_text', models.TextField(blank=True, default=None, null=True, verbose_name='详细信息')),
                ('is_notice', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], default=0, verbose_name='是否发送通知')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='monitoring.monitoringtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '预警监控报告',
                'verbose_name_plural': '预警监控报告',
                'db_table': 'monitoring_report',
                'ordering': ['-create_time'],
            },
        ),
    ]
