# Generated by Django 4.1.5 on 2026-01-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_system', '0014_tasks_fail_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('script_content', models.TextField()),
                ('script_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('log_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '待执行'), (1, '运行中'), (2, '已停止'), (3, '失败'), (4, '已完成')], default=0, verbose_name='状态')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'monitoring_task',
                'ordering': ['-create_time'],
            },
        ),
    ]
