# Generated by Django 4.1.5 on 2026-01-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringtask',
            name='script_content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoringtask',
            name='script_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
