# Generated by Django 4.1.5 on 2026-01-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0014_tasks_fail_notice'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringtask',
            name='is_notice',
            field=models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], default=0, verbose_name='是否发送通知'),
        ),
        migrations.AddField(
            model_name='monitoringtask',
            name='notice_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.noticegroup', verbose_name='通知组'),
        ),
        migrations.CreateModel(
            name='MonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.SmallIntegerField(choices=[(0, '信息'), (1, '失败'), (2, '警告'), (3, '调试')], default=0, verbose_name='状态')),
                ('msg', models.TextField(blank=True, default=None, null=True, verbose_name='消息内容')),
                ('send_text', models.TextField(blank=True, default=None, null=True, verbose_name='详细信息')),
                ('is_notice', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], default=0, verbose_name='是否发送通知')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='monitoring.monitoringtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '预警监控报告',
                'verbose_name_plural': '预警监控报告',
                'db_table': 'monitoring_report',
                'ordering': ['-create_time'],
            },
        ),
    ]
