# Generated by Django 4.1.5 on 2026-05-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_system', '0017_database_db_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFactoryDatasourceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='逻辑数据源名称')),
                ('code', models.CharField(max_length=64, verbose_name='逻辑数据源编码')),
                ('db_type', models.SmallIntegerField(default=0, verbose_name='数据库类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], db_index=True, default=1, verbose_name='状态')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'data_factory_datasource_alias',
                'ordering': ['-id'],
                'unique_together': {('project_product', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DataFactoryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='实体名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='实体描述')),
                ('table_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='表名')),
                ('primary_key', models.CharField(default='id', max_length=128, verbose_name='主键字段')),
                ('unique_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='唯一字段')),
                ('create_type', models.SmallIntegerField(choices=[(1, 'API'), (2, 'SQL'), (3, '自定义函数')], default=2, verbose_name='创建方式')),
                ('delete_type', models.SmallIntegerField(choices=[(1, 'API'), (2, 'SQL'), (3, '自定义函数')], default=2, verbose_name='删除方式')),
                ('cleanup_order', models.IntegerField(default=100, verbose_name='清理顺序')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], db_index=True, default=1, verbose_name='状态')),
                ('datasource_alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_data_factory.datafactorydatasourcealias')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_system.productmodule')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'data_factory_entity',
                'ordering': ['-id'],
                'unique_together': {('project_product', 'datasource_alias', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='DataFactoryExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cleanup_time', models.DateTimeField(blank=True, null=True, verbose_name='清理时间')),
                ('execution_no', models.CharField(max_length=64, unique=True, verbose_name='执行编号')),
                ('source_type', models.SmallIntegerField(choices=[(1, '模板调试'), (2, '手动执行'), (3, '系统调用'), (4, 'API用例'), (5, 'API接口场景')], default=1, verbose_name='执行来源')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源ID')),
                ('stage', models.SmallIntegerField(choices=[(1, '调试'), (2, '创建'), (3, '清理')], default=1, verbose_name='执行阶段')),
                ('status', models.SmallIntegerField(choices=[(1, '待执行'), (2, '成功'), (3, '失败'), (4, '进行中')], db_index=True, default=1, verbose_name='执行状态')),
                ('cleanup_status', models.SmallIntegerField(choices=[(0, '未清理'), (1, '已清理'), (2, '清理失败'), (3, '跳过清理')], db_index=True, default=0, verbose_name='清理状态')),
                ('context', models.JSONField(default=dict, verbose_name='执行上下文')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_system.productmodule')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'data_factory_execution',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DataFactoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('field_overrides', models.JSONField(default=dict, verbose_name='字段覆盖')),
                ('output_config', models.JSONField(default=list, verbose_name='输出配置')),
                ('cleanup_strategy', models.SmallIntegerField(choices=[(1, '执行结束'), (2, '手动清理'), (3, '不清理')], default=2, verbose_name='默认清理策略')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], db_index=True, default=1, verbose_name='状态')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_data_factory.datafactoryentity')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_system.productmodule')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'data_factory_template',
                'ordering': ['-id'],
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataFactoryExecutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cleanup_time', models.DateTimeField(blank=True, null=True, verbose_name='清理时间')),
                ('alias', models.CharField(max_length=64, verbose_name='上下文别名')),
                ('primary_value', models.CharField(blank=True, max_length=256, null=True, verbose_name='主键值')),
                ('data', models.JSONField(default=dict, verbose_name='创建数据')),
                ('cleanup_strategy', models.SmallIntegerField(choices=[(1, '执行结束'), (2, '手动清理'), (3, '不清理')], default=2, verbose_name='清理策略')),
                ('cleanup_order', models.IntegerField(default=100, verbose_name='清理顺序')),
                ('cleanup_status', models.SmallIntegerField(choices=[(0, '未清理'), (1, '已清理'), (2, '清理失败'), (3, '跳过清理')], db_index=True, default=0, verbose_name='清理状态')),
                ('cleanup_error', models.TextField(blank=True, null=True, verbose_name='清理错误')),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_system.database')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_data_factory.datafactoryexecution')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_data_factory.datafactorytemplate')),
            ],
            options={
                'db_table': 'data_factory_execution_item',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='datafactoryexecution',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_data_factory.datafactorytemplate'),
        ),
        migrations.AddField(
            model_name='datafactoryexecution',
            name='test_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_system.testobject'),
        ),
        migrations.CreateModel(
            name='DataFactoryCaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('source_type', models.SmallIntegerField(choices=[(1, 'API用例'), (2, 'UI用例'), (3, 'API接口场景')], db_index=True, verbose_name='用例类型')),
                ('source_id', models.IntegerField(db_index=True, verbose_name='用例ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据名称')),
                ('stage', models.SmallIntegerField(default=1, verbose_name='执行阶段')),
                ('sort', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('field_overrides', models.JSONField(default=dict, verbose_name='字段覆盖')),
                ('cleanup_strategy', models.SmallIntegerField(blank=True, null=True, verbose_name='清理策略覆盖')),
                ('status', models.SmallIntegerField(db_index=True, default=1, verbose_name='状态')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_data_factory.datafactorytemplate')),
            ],
            options={
                'db_table': 'data_factory_case_config',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataFactoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128, verbose_name='字段名')),
                ('label', models.CharField(blank=True, max_length=128, null=True, verbose_name='字段说明')),
                ('db_type', models.CharField(max_length=128, verbose_name='数据库类型')),
                ('platform_type', models.CharField(max_length=32, verbose_name='平台类型')),
                ('nullable', models.BooleanField(default=True, verbose_name='是否可空')),
                ('primary_key', models.BooleanField(default=False, verbose_name='是否主键')),
                ('autoincrement', models.BooleanField(default=False, verbose_name='是否自增')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='最大长度')),
                ('enum_values', models.JSONField(default=list, verbose_name='枚举值')),
                ('generator_type', models.SmallIntegerField(choices=[(0, '跳过'), (1, '固定值'), (2, '随机字符串（长度8）'), (3, '随机整数（1-100）'), (4, '随机小数（1-100，2位）'), (5, '当前时间'), (6, '相对时间'), (7, 'UUID'), (9, '枚举值'), (11, '依赖实体字段'), (13, '测试数据方法')], default=1, verbose_name='生成方式')),
                ('generator_config', models.JSONField(default=dict, verbose_name='生成配置')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_data_factory.datafactoryentity')),
            ],
            options={
                'db_table': 'data_factory_field',
                'ordering': ['sort', 'id'],
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataFactoryDatasourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], db_index=True, default=1, verbose_name='状态')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.database')),
                ('datasource_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_data_factory.datafactorydatasourcealias')),
                ('test_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.testobject')),
            ],
            options={
                'db_table': 'data_factory_datasource_binding',
                'ordering': ['-id'],
                'unique_together': {('datasource_alias', 'test_object')},
            },
        ),
        migrations.AddIndex(
            model_name='datafactorycaseconfig',
            index=models.Index(fields=['source_type', 'source_id', 'stage', 'status'], name='data_factor_source__0d0fdb_idx'),
        ),
    ]
