# Generated by Django 4.1.5 on 2026-05-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0002_update_execution_status_enum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafactoryexecution',
            name='test_object',
        ),
    ]
