# Generated by Django 4.1.5 on 2026-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0003_remove_datafactoryexecution_test_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactorytemplate',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否默认模板'),
        ),
    ]
