# Generated by Django 4.1.5 on 2026-05-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0006_datafactorytemplateitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafactorytemplateitem',
            name='cleanup_strategy',
        ),
        migrations.RemoveField(
            model_name='datafactorytemplateitem',
            name='enabled',
        ),
    ]
