# Generated by Django 4.1.5 on 2026-03-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_system', '0016_testsuitedetails_idx_suite_type_status'),
        ('auto_user', '0003_userlogs_method_userlogs_request_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=255, verbose_name='需求名称')),
                ('input_type', models.SmallIntegerField(db_index=True, default=0, verbose_name='输入类型')),
                ('input_content', models.TextField(blank=True, null=True, verbose_name='输入内容（文本/URL）')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='ai_requirement/', verbose_name='上传文件（图片/Word）')),
                ('status', models.SmallIntegerField(db_index=True, default=0, verbose_name='处理状态')),
                ('ai_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='AI模型快照')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='失败信息')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_user.user', verbose_name='创建人')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.productmodule', verbose_name='产品模块')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct', verbose_name='项目产品')),
            ],
            options={
                'db_table': 'ai_requirement',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AiRequirementSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=255, verbose_name='子模块名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='子模块功能描述')),
                ('sort', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_confirmed', models.SmallIntegerField(db_index=True, default=0, verbose_name='确认状态')),
                ('ai_raw', models.TextField(blank=True, null=True, verbose_name='AI原始输出')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.productmodule', verbose_name='产品模块')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct', verbose_name='项目产品')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_ai.airequirement', verbose_name='所属需求')),
            ],
            options={
                'db_table': 'ai_requirement_split',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiTestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=255, verbose_name='测试点名称')),
                ('test_type', models.SmallIntegerField(db_index=True, default=0, verbose_name='测试点类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='测试点描述')),
                ('is_confirmed', models.SmallIntegerField(db_index=True, default=0, verbose_name='确认状态')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.productmodule', verbose_name='产品模块')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct', verbose_name='项目产品')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_ai.airequirement', verbose_name='所属需求')),
                ('requirement_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_ai.airequirementsplit', verbose_name='所属子模块')),
            ],
            options={
                'db_table': 'ai_test_point',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('case_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='用例编号')),
                ('title', models.CharField(max_length=512, verbose_name='用例标题')),
                ('module_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属模块名称')),
                ('case_type', models.SmallIntegerField(db_index=True, default=0, verbose_name='用例类型')),
                ('priority', models.SmallIntegerField(db_index=True, default=1, verbose_name='优先级')),
                ('version', models.CharField(blank=True, max_length=64, null=True, verbose_name='版本编号')),
                ('precondition', models.TextField(blank=True, null=True, verbose_name='前置条件')),
                ('steps', models.JSONField(default=list, verbose_name='测试步骤')),
                ('expected', models.TextField(verbose_name='预期结果')),
                ('dev_test_result', models.SmallIntegerField(default=0, verbose_name='开发自测结果')),
                ('test_result', models.SmallIntegerField(db_index=True, default=0, verbose_name='测试结果')),
                ('pre_release_result', models.SmallIntegerField(default=0, verbose_name='预发结果')),
                ('auto_tag', models.SmallIntegerField(default=0, verbose_name='自动化标识')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注/附件')),
                ('status', models.SmallIntegerField(db_index=True, default=0, verbose_name='用例状态')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.productmodule', verbose_name='产品模块')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct', verbose_name='项目产品')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_ai.airequirement', verbose_name='所属需求')),
                ('requirement_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_ai.airequirementsplit', verbose_name='所属子模块')),
                ('test_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_ai.aitestpoint', verbose_name='所属测试点')),
            ],
            options={
                'db_table': 'ai_test_case',
                'ordering': ['case_no', 'id'],
            },
        ),
    ]
