# Generated by Django 4.1.5 on 2025-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0008_delete_uiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageelement',
            name='exp2',
            field=models.SmallIntegerField(null=True, verbose_name='元素表达式'),
        ),
        migrations.AddField(
            model_name='pageelement',
            name='exp3',
            field=models.SmallIntegerField(null=True, verbose_name='元素表达式'),
        ),
        migrations.AddField(
            model_name='pageelement',
            name='loc2',
            field=models.TextField(null=True, verbose_name='元素定位'),
        ),
        migrations.AddField(
            model_name='pageelement',
            name='loc3',
            field=models.TextField(null=True, verbose_name='元素定位'),
        ),
    ]
