# Generated by Django 4.1.5 on 2025-10-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0010_pageelement_sub2_pageelement_sub3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageelement',
            name='prompt',
            field=models.TextField(null=True, verbose_name='AI元素定位提示词'),
        ),
    ]
