# Generated by Django 4.1.5 on 2026-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0012_alter_pagesteps_status_alter_uicase_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicase',
            name='scenario_description',
            field=models.TextField(blank=True, null=True, verbose_name='场景描述'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='scenario_tags',
            field=models.JSONField(default=list, verbose_name='场景标签'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='scenario_type',
            field=models.SmallIntegerField(default=0, verbose_name='场景类型'),
        ),
        migrations.AddField(
            model_name='uipublic',
            name='test_env',
            field=models.SmallIntegerField(blank=True, choices=[(0, '测试环境'), (1, '预发环境'), (2, '生产环境'), (3, '开发环境'), (4, '验收环境'), (5, '仿真环境')], default=None, null=True, verbose_name='测试环境'),
        ),
    ]
