# Generated by Django 4.1.5 on 2023-03-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auto_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.SmallIntegerField(verbose_name='环境备注')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='被测试的对象')),
                ('value', models.CharField(max_length=1024, verbose_name='被测试的对象')),
                ('test_type', models.SmallIntegerField(verbose_name='对应什么客户端')),
                ('executor_name', models.CharField(max_length=64, null=True, verbose_name='负责人')),
                ('team',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project',
                                   to_field='name')),
            ],
            options={
                'db_table': 'test_obj',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NoticeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='通知名称')),
                ('config', models.CharField(max_length=1028, verbose_name='通知配置')),
                ('state', models.SmallIntegerField(null=True, verbose_name='是否选中发送')),
                ('team',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project',
                                   to_field='name')),
            ],
            options={
                'db_table': 'notice_config',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='数据库名称')),
                ('user', models.CharField(max_length=64, null=True, verbose_name='登录用户名')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='登录密码')),
                ('host', models.CharField(max_length=64, null=True, verbose_name='数据库地址')),
                ('post', models.IntegerField(null=True, verbose_name='端口')),
                ('team',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project',
                                   to_field='name')),
                ('test_obj',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.testobject',
                                   to_field='name')),
            ],
            options={
                'db_table': 'data_base',
                'ordering': ['-id'],
            },
        ),
    ]
