# Generated by Django 4.1.5 on 2024-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='test_obj',
        ),
        migrations.AddField(
            model_name='database',
            name='environment',
            field=models.SmallIntegerField(null=True, verbose_name='环境类型'),
        ),
        migrations.AddField(
            model_name='noticeconfig',
            name='environment',
            field=models.SmallIntegerField(null=True, verbose_name='环境类型'),
        ),
    ]
