# Generated by Django 4.1.5 on 2023-10-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='state',
            field=models.SmallIntegerField(null=True, verbose_name='是否启用'),
        ),
    ]
