# Generated by Django 4.1.5 on 2024-11-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksdetails',
            old_name='case',
            new_name='case_id',
        ),
        migrations.AddField(
            model_name='testsuitedetails',
            name='retry',
            field=models.SmallIntegerField(default=0, verbose_name='重试次数'),
            preserve_default=False,
        ),
    ]
