# Generated by Django 4.1.5 on 2024-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksdetails',
            name='command',
            field=models.TextField(null=True, verbose_name='命令'),
        ),
        migrations.AlterField(
            model_name='tasksdetails',
            name='case_id',
            field=models.SmallIntegerField(null=True, verbose_name='用例ID'),
        ),
    ]
