# Generated by Django 4.1.5 on 2023-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='定时策略名称')),
                ('trigger_type', models.CharField(max_length=64, verbose_name='触发器类型')),
                ('time_company', models.CharField(max_length=64, verbose_name='单位')),
                ('hour', models.SmallIntegerField(verbose_name='小时')),
            ],
            options={
                'db_table': 'time_tasks',
                'ordering': ['-id'],
            },
        ),
    ]
