# Generated by Django 4.1.5 on 2024-11-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0002_remove_testsuite_project_testsuite_project_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
        migrations.AddField(
            model_name='tasks',
            name='project_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.projectproduct'),
        ),
    ]
