# Generated by Django 4.1.5 on 2024-11-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0002_rename_case_tasksdetails_case_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproduct',
            name='auto_type',
        ),
    ]
