# Generated by Django 4.1.5 on 2024-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0002_remove_database_test_obj_database_environment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuitereport',
            name='test_object',
        ),
        migrations.AddField(
            model_name='testsuitereport',
            name='test_env',
            field=models.SmallIntegerField(null=True, verbose_name='测试环境'),
        ),
    ]
