# Generated by Django 4.1.5 on 2023-03-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0002_timetasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetasks',
            name='hour',
            field=models.SmallIntegerField(null=True, verbose_name='小时'),
        ),
        migrations.AlterField(
            model_name='timetasks',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='定时策略名称'),
        ),
        migrations.AlterField(
            model_name='timetasks',
            name='time_company',
            field=models.CharField(max_length=64, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='timetasks',
            name='trigger_type',
            field=models.CharField(max_length=64, null=True, verbose_name='触发器类型'),
        ),
    ]
