# Generated by Django 4.1.5 on 2024-11-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0003_remove_tasks_project_tasks_project_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdetails',
            name='case_id',
            field=models.SmallIntegerField(verbose_name='用例ID'),
        ),
    ]
