# Generated by Django 4.1.5 on 2023-05-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0003_remove_noticeconfig_name_noticeconfig_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testobject',
            name='team',
        ),
    ]
