# Generated by Django 4.1.5 on 2023-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0003_alter_timetasks_hour_alter_timetasks_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetasks',
            name='time_company',
        ),
        migrations.AddField(
            model_name='timetasks',
            name='day',
            field=models.CharField(max_length=64, null=True, verbose_name='天'),
        ),
        migrations.AddField(
            model_name='timetasks',
            name='minute',
            field=models.CharField(max_length=64, null=True, verbose_name='分钟'),
        ),
        migrations.AddField(
            model_name='timetasks',
            name='month',
            field=models.CharField(max_length=64, null=True, verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='timetasks',
            name='hour',
            field=models.CharField(max_length=64, null=True, verbose_name='小时'),
        ),
    ]
