# Generated by Django 4.1.5 on 2024-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0003_remove_testsuitereport_test_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='test_obj',
        ),
        migrations.AddField(
            model_name='scheduledtasks',
            name='test_env',
            field=models.SmallIntegerField(null=True, verbose_name='测试环境'),
        ),
    ]
