# Generated by Django 4.1.5 on 2023-05-13 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0002_user_mailbox'),
        ('auto_system', '0004_remove_testobject_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='testobject',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project'),
        ),
    ]
