# Generated by Django 4.1.5 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0004_remove_timetasks_time_company_timetasks_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetasks',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='定时策略名称'),
        ),
    ]
