# Generated by Django 4.1.5 on 2023-10-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0005_testsuitereport_delete_testreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitereport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
