# Generated by Django 4.1.5 on 2023-10-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0006_alter_testsuitereport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitereport',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
