# Generated by Django 4.1.5 on 2024-11-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0006_rename_result_testsuitedetails_result_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproduct',
            name='auto_type',
            field=models.SmallIntegerField(default=1, verbose_name='自动化类型'),
            preserve_default=False,
        ),
    ]
