# Generated by Django 4.1.5 on 2024-11-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0007_scheduledtasks_cron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='cron',
        ),
        migrations.RemoveField(
            model_name='timetasks',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetasks',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timetasks',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='timetasks',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='timetasks',
            name='month',
        ),
        migrations.RemoveField(
            model_name='timetasks',
            name='trigger_type',
        ),
        migrations.AddField(
            model_name='timetasks',
            name='cron',
            field=models.CharField(max_length=64, null=True, verbose_name='cron表达式'),
        ),
    ]
