# Generated by Django 4.1.5 on 2023-10-26 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0007_alter_testsuitereport_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuitereport',
            options={},
        ),
    ]
