# Generated by Django 4.1.5 on 2023-10-30 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0008_alter_testsuitereport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuitereport',
            options={'ordering': ['-create_time']},
        ),
    ]
