# Generated by Django 4.1.5 on 2024-11-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0008_testsuitedetails_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='noticeconfig',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='是否选中发送'),
        ),
    ]
