# Generated by Django 4.1.5 on 2023-11-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0009_alter_testsuitereport_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='noticeconfig',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='testsuitereport',
            old_name='run_state',
            new_name='run_status',
        ),
        migrations.RenameField(
            model_name='testsuitereport',
            old_name='state',
            new_name='status',
        ),
    ]
