# Generated by Django 4.1.5 on 2023-11-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0011_rename_post_database_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuitereport',
            name='name',
        ),
        migrations.AddField(
            model_name='testsuitereport',
            name='error_message',
            field=models.CharField(max_length=64, null=True, verbose_name='错误提示'),
        ),
    ]
