# Generated by Django 4.1.5 on 2023-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0012_remove_testsuitereport_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitereport',
            name='error_message',
            field=models.TextField(null=True, verbose_name='错误提示'),
        ),
    ]
