# Generated by Django 4.1.5 on 2023-12-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0014_testsuitereport_test_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='status',
        ),
        migrations.AddField(
            model_name='testobject',
            name='status',
            field=models.SmallIntegerField(null=True, verbose_name='是否启用'),
        ),
    ]
