# Generated by Django 4.1.5 on 2023-12-26 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0015_remove_database_status_testobject_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testobject',
            old_name='status',
            new_name='db_status',
        ),
    ]
