# Generated by Django 4.1.5 on 2023-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0016_rename_status_testobject_db_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtasks',
            name='is_notice',
            field=models.SmallIntegerField(null=True, verbose_name='是否发送通知'),
        ),
    ]
