# Generated by Django 4.1.5 on 2023-12-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0017_scheduledtasks_is_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetasks',
            name='day_of_week',
            field=models.CharField(max_length=64, null=True, verbose_name='周'),
        ),
    ]
