# Generated by Django 4.1.5 on 2024-01-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0018_timetasks_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksruncaselist',
            name='api_case',
            field=models.SmallIntegerField(null=True, verbose_name='api_case_id'),
        ),
    ]
