# Generated by Django 4.1.5 on 2024-01-02 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0019_tasksruncaselist_api_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksruncaselist',
            old_name='api_case',
            new_name='case',
        ),
        migrations.RemoveField(
            model_name='tasksruncaselist',
            name='ui_case',
        ),
    ]
