# Generated by Django 4.1.5 on 2024-01-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0020_rename_api_case_tasksruncaselist_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('describe', models.CharField(max_length=1024, null=True, verbose_name='描述')),
                ('key', models.CharField(max_length=128, verbose_name='key')),
                ('value', models.TextField(null=True, verbose_name='value')),
                ('value_type', models.SmallIntegerField(null=True, verbose_name='value的类型枚举')),
                ('case_type', models.SmallIntegerField(null=True, verbose_name='用例类型')),
                ('case_id', models.SmallIntegerField(null=True, verbose_name='绑定的用例ID')),
            ],
            options={
                'db_table': 'cache_data',
            },
        ),
    ]
