# Generated by Django 4.1.5 on 2024-02-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0022_scheduledtasks_parallel_number_tasksruncaselist_sort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testobject',
            name='db_status',
        ),
        migrations.AddField(
            model_name='testobject',
            name='db_c_status',
            field=models.SmallIntegerField(null=True, verbose_name='查询权限'),
        ),
        migrations.AddField(
            model_name='testobject',
            name='db_rud_status',
            field=models.SmallIntegerField(null=True, verbose_name='增删改权限'),
        ),
    ]
