# Generated by Django 4.1.5 on 2024-04-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0023_rename_settings_noticeconfig_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='parallel_number',
        ),
        migrations.AddField(
            model_name='testsuitereport',
            name='case_list',
            field=models.JSONField(null=True, verbose_name='测试套包含的用例列表'),
        ),
        migrations.AddField(
            model_name='testsuitereport',
            name='is_notice',
            field=models.SmallIntegerField(null=True, verbose_name='是否发送通知'),
        ),
    ]
