# Generated by Django 4.1.5 on 2024-04-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0008_alter_userlogs_options_userlogs_source_type'),
        ('auto_system', '0024_remove_scheduledtasks_parallel_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='executor_name',
        ),
        migrations.AddField(
            model_name='scheduledtasks',
            name='case_executor',
            field=models.JSONField(null=True, verbose_name='用例执行人'),
        ),
        migrations.AddField(
            model_name='scheduledtasks',
            name='case_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user', verbose_name='用例责任人'),
        ),
        migrations.AddField(
            model_name='testsuitereport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user', verbose_name='用例责任人'),
        ),
    ]
