# Generated by Django 4.1.5 on 2024-11-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uiconfig',
            old_name='user_id',
            new_name='user',
        ),
    ]
