# Generated by Django 4.1.5 on 2024-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiconfig',
            name='device',
            field=models.CharField(max_length=64, null=True, verbose_name='浏览器模式'),
        ),
    ]
