# Generated by Django 4.1.5 on 2023-03-12 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runsort',
            name='loc_name',
        ),
        migrations.AddField(
            model_name='runsort',
            name='el_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uielement',
                                    to_field='name'),
        ),
        migrations.AlterField(
            model_name='runsort',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uicase',
                                    to_field='name'),
        ),
    ]
