# Generated by Django 4.1.5 on 2023-10-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiconfig',
            name='browser_type',
            field=models.SmallIntegerField(null=True, verbose_name='浏览器类型'),
        ),
    ]
