# Generated by Django 4.1.5 on 2024-11-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0002_rename_user_id_uiconfig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesteps',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='uicasestepsdetailed',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='uiconfig',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='uipublic',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状态'),
        ),
    ]
