# Generated by Django 4.1.5 on 2023-10-17 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0002_uiconfig_browser_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uicasestepsdetailed',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='case_cache_data',
            field=models.CharField(max_length=3000, null=True, verbose_name='用例缓存数据'),
        ),
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='case_sort',
            field=models.IntegerField(null=True, verbose_name='用例排序'),
        ),
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='page_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uipagesteps'),
        ),
        migrations.AddField(
            model_name='uipagestepsdetailed',
            name='debug_data',
            field=models.CharField(max_length=64, null=True, verbose_name='调试用的数据'),
        ),
        migrations.AlterModelTable(
            name='uicasestepsdetailed',
            table='ui_case_steps_detailed',
        ),
    ]
