# Generated by Django 4.1.5 on 2023-05-07 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0002_remove_runsort_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uielement',
            name='team',
        ),
    ]
