# Generated by Django 4.1.5 on 2024-07-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0002_uiconfig_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uipage',
            name='type',
        ),
    ]
