# Generated by Django 4.1.5 on 2024-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0003_remove_uipage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uipublic',
            name='value',
            field=models.TextField(null=True, verbose_name='值'),
        ),
    ]
