# Generated by Django 4.1.5 on 2023-05-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0002_user_mailbox'),
        ('auto_ui', '0003_remove_uielement_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicasegroup',
            name='case_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='related_case_people', to='auto_user.user', verbose_name='用例责任人'),
        ),
        migrations.AddField(
            model_name='uicasegroup',
            name='timing_actuator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='related_timing_actuator', to='auto_user.user',
                                    verbose_name='定时执行的设备'),
        ),
    ]
