# Generated by Django 4.1.5 on 2023-03-25 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0001_initial'),
        ('auto_ui', '0003_uiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiresult',
            name='msg',
            field=models.CharField(max_length=1048, null=True, verbose_name='失败提示日志'),
        ),
        migrations.AddField(
            model_name='uiresult',
            name='picture',
            field=models.CharField(max_length=1048, null=True, verbose_name='图片路径或名称'),
        ),
        migrations.AlterField(
            model_name='uiresult',
            name='existence',
            field=models.SmallIntegerField(null=True, verbose_name='元素执行的情况'),
        ),
        migrations.CreateModel(
            name='UiPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('key', models.CharField(max_length=128, null=True, verbose_name='键')),
                ('value', models.CharField(max_length=2048, null=True, verbose_name='值')),
                ('state', models.SmallIntegerField(null=True, verbose_name='状态')),
                ('type', models.SmallIntegerField(null=True, verbose_name='公共类型')),
                ('team',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project',
                                   to_field='name')),
            ],
            options={
                'db_table': 'ui_public',
                'ordering': ['-id'],
            },
        ),
    ]
