# Generated by Django 4.1.5 on 2023-10-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0003_alter_uicasestepsdetailed_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uiconfig',
            old_name='local_port',
            new_name='browser_port',
        ),
        migrations.RemoveField(
            model_name='uiconfig',
            name='package',
        ),
        migrations.AddField(
            model_name='uiconfig',
            name='state',
            field=models.SmallIntegerField(default=21312, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uipagestepsdetailed',
            name='debug_data',
            field=models.CharField(max_length=1048, null=True, verbose_name='调试用的数据'),
        ),
    ]
