# Generated by Django 4.1.5 on 2024-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0004_alter_uipublic_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicaseresult',
            name='video_path',
            field=models.CharField(max_length=1024, null=True, verbose_name='视频路径'),
        ),
    ]
