# Generated by Django 4.1.5 on 2023-10-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0004_rename_local_port_uiconfig_browser_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiconfig',
            name='type',
            field=models.SmallIntegerField(default=1, verbose_name='什么客户端'),
            preserve_default=False,
        ),
    ]
