# Generated by Django 4.1.5 on 2023-03-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0005_remove_uicasegroup_fail_remove_uicasegroup_res_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uielement',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uipage',
                                    to_field='name'),
        ),
    ]
