# Generated by Django 4.1.5 on 2024-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0005_uicaseresult_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipagestepsdetailed',
            name='ope_key',
            field=models.CharField(max_length=1048, null=True, verbose_name='对该元素的操作类型'),
        ),
        migrations.AlterField(
            model_name='uipagestepsdetailed',
            name='ope_value',
            field=models.TextField(null=True, verbose_name='对该元素的操作类型'),
        ),
    ]
