# Generated by Django 4.1.5 on 2023-10-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0005_uiconfig_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiconfig',
            name='state',
            field=models.SmallIntegerField(null=True, verbose_name='状态'),
        ),
    ]
