# Generated by Django 4.1.5 on 2023-10-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0006_alter_uiconfig_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiconfig',
            name='type',
            field=models.SmallIntegerField(null=True, verbose_name='什么客户端'),
        ),
    ]
