# Generated by Django 4.1.5 on 2024-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0006_uipagestepsdetailed_ope_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uipagestepsdetailed',
            name='ope_value',
            field=models.JSONField(null=True, verbose_name='对该元素的操作类型'),
        ),
    ]
