# Generated by Django 4.1.5 on 2023-05-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0006_alter_noticeconfig_config'),
        ('auto_ui', '0006_runsort_el_name_b_alter_runsort_el_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiCaseGroupEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(null=True, verbose_name='执行顺序的展示')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uicase')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uicasegroup')),
                ('test_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.testobject')),
            ],
            options={
                'db_table': 'ui_case_group_environment',
            },
        ),
    ]
