# Generated by Django 4.1.5 on 2023-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0006_alter_uielement_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsort',
            name='ope_value_key',
            field=models.CharField(max_length=64, null=True, verbose_name='输入内容的key，用来保存变量'),
        ),
    ]
