# Generated by Django 4.1.5 on 2023-10-22 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0007_alter_uiconfig_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uipublic',
            name='type',
        ),
    ]
