# Generated by Django 4.1.5 on 2023-04-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0005_alter_timetasks_name'),
        ('auto_ui', '0007_runsort_ope_value_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicasegroup',
            name='test_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.testobject'),
        ),
    ]
