# Generated by Django 4.1.5 on 2023-10-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0008_remove_uipublic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('test_set_id', models.IntegerField(null=True, verbose_name='测试套件id')),
                ('case_id', models.IntegerField(null=True, verbose_name='用例ID')),
                ('case_name', models.CharField(max_length=64, null=True, verbose_name='用例名称')),
                ('module_name', models.CharField(max_length=64, null=True, verbose_name='模块名称')),
                ('case_people', models.CharField(max_length=64, null=True, verbose_name='负责人名称')),
                ('test_obj', models.CharField(max_length=1024, null=True, verbose_name='测试环境')),
                ('case_cache_data', models.TextField(null=True, verbose_name='用例缓存数据')),
                ('status', models.SmallIntegerField(null=True, verbose_name='用例测试结果')),
            ],
            options={
                'db_table': 'ui_case_result',
            },
        ),
        migrations.CreateModel(
            name='UiEleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ele_name_a', models.CharField(max_length=64, null=True, verbose_name='元素名称A')),
                ('ele_name_b', models.CharField(max_length=64, null=True, verbose_name='元素名称B')),
                ('ele_quantity', models.SmallIntegerField(null=True, verbose_name='元素个数')),
                ('status', models.SmallIntegerField(null=True, verbose_name='元素测试结果')),
                ('picture_path', models.CharField(max_length=1000, null=True, verbose_name='用例名称')),
            ],
            options={
                'db_table': 'ui_ele_result',
            },
        ),
        migrations.CreateModel(
            name='UiPageStepsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('page_step_name', models.CharField(max_length=64, null=True, verbose_name='步骤名称')),
                ('status', models.SmallIntegerField(null=True, verbose_name='步骤测试结果')),
            ],
            options={
                'db_table': 'ui_page_steps_result',
            },
        ),
    ]
