# Generated by Django 4.1.5 on 2024-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0008_remove_uieleresult_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uiconfig',
            name='browser_path',
        ),
        migrations.RemoveField(
            model_name='uiconfig',
            name='browser_port',
        ),
        migrations.RemoveField(
            model_name='uiconfig',
            name='browser_type',
        ),
        migrations.RemoveField(
            model_name='uiconfig',
            name='device',
        ),
        migrations.RemoveField(
            model_name='uiconfig',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='uiconfig',
            name='is_headless',
        ),
        migrations.AddField(
            model_name='uiconfig',
            name='config',
            field=models.JSONField(null=True, verbose_name='配置json'),
        ),
    ]
