# Generated by Django 4.1.5 on 2023-10-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0009_uicaseresult_uieleresult_uipagestepsresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uicaseresult',
            name='test_set_id',
        ),
        migrations.AddField(
            model_name='uicaseresult',
            name='test_suite_id',
            field=models.BigIntegerField(null=True, verbose_name='测试套件id'),
        ),
    ]
