# Generated by Django 4.1.5 on 2023-10-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0010_remove_uicaseresult_test_set_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uieleresult',
            name='test_suite_id',
            field=models.BigIntegerField(null=True, verbose_name='测试套件id'),
        ),
        migrations.AddField(
            model_name='uipagestepsresult',
            name='test_suite_id',
            field=models.BigIntegerField(null=True, verbose_name='测试套件id'),
        ),
    ]
