# Generated by Django 4.1.5 on 2023-10-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0011_uieleresult_test_suite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uieleresult',
            name='page_step_id',
            field=models.IntegerField(null=True, verbose_name='步骤id'),
        ),
        migrations.AddField(
            model_name='uipagestepsresult',
            name='page_step_id',
            field=models.IntegerField(null=True, verbose_name='步骤id'),
        ),
    ]
