# Generated by Django 4.1.5 on 2023-10-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0012_uieleresult_page_step_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipagestepsresult',
            name='case_id',
            field=models.IntegerField(null=True, verbose_name='用例ID'),
        ),
    ]
