# Generated by Django 4.1.5 on 2023-10-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0014_uieleresult_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uieleresult',
            name='ass_type',
            field=models.CharField(max_length=1048, null=True, verbose_name='断言类型'),
        ),
        migrations.AddField(
            model_name='uieleresult',
            name='ass_value',
            field=models.CharField(max_length=1048, null=True, verbose_name='操作内容'),
        ),
        migrations.AddField(
            model_name='uieleresult',
            name='exp',
            field=models.SmallIntegerField(null=True, verbose_name='元素表达式'),
        ),
        migrations.AddField(
            model_name='uieleresult',
            name='loc',
            field=models.CharField(max_length=1048, null=True, verbose_name='元素定位'),
        ),
        migrations.AddField(
            model_name='uieleresult',
            name='ope_type',
            field=models.CharField(max_length=1048, null=True, verbose_name='对该元素的操作类型'),
        ),
        migrations.AddField(
            model_name='uieleresult',
            name='ope_value',
            field=models.CharField(max_length=1048, null=True, verbose_name='操作内容'),
        ),
        migrations.AddField(
            model_name='uieleresult',
            name='sleep',
            field=models.IntegerField(null=True, verbose_name='等待时间'),
        ),
        migrations.AddField(
            model_name='uieleresult',
            name='sub',
            field=models.IntegerField(null=True, verbose_name='下标'),
        ),
    ]
