# Generated by Django 4.1.5 on 2023-11-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0016_remove_uipagestepsdetailed_debug_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='case_cache_ass',
            field=models.TextField(null=True, verbose_name='步骤缓存断言'),
        ),
        migrations.AlterField(
            model_name='uicasestepsdetailed',
            name='case_cache_data',
            field=models.TextField(null=True, verbose_name='用例缓存数据'),
        ),
    ]
