# Generated by Django 4.1.5 on 2023-11-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0018_uiconfig_is_headless'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uicase',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='uiconfig',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='uipublic',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='uicaseresult',
            name='case_cache_data',
            field=models.JSONField(null=True, verbose_name='用例缓存数据'),
        ),
        migrations.AlterField(
            model_name='uicasestepsdetailed',
            name='case_cache_ass',
            field=models.JSONField(null=True, verbose_name='步骤缓存断言'),
        ),
        migrations.AlterField(
            model_name='uicasestepsdetailed',
            name='case_cache_data',
            field=models.JSONField(null=True, verbose_name='用例缓存数据'),
        ),
        migrations.AlterField(
            model_name='uieleresult',
            name='ass_value',
            field=models.JSONField(max_length=1048, null=True, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='uieleresult',
            name='ope_value',
            field=models.JSONField(max_length=1048, null=True, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='uipagestepsdetailed',
            name='ass_value',
            field=models.JSONField(null=True, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='uipagestepsdetailed',
            name='ope_value',
            field=models.JSONField(null=True, verbose_name='操作内容'),
        ),
    ]
