# Generated by Django 4.1.5 on 2023-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0020_uipage_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uieleresult',
            name='msg',
            field=models.CharField(max_length=2048, null=True, verbose_name='元素错误提示语'),
        ),
    ]
