# Generated by Django 4.1.5 on 2023-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0022_uielement_is_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uielement',
            name='is_iframe',
            field=models.SmallIntegerField(null=True, verbose_name='是否在iframe里面'),
        ),
    ]
