# Generated by Django 4.1.5 on 2023-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0023_alter_uielement_is_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='uielement',
            name='locator',
            field=models.CharField(max_length=1048, null=True, verbose_name='元素定位'),
        ),
    ]
