# Generated by Django 4.1.5 on 2023-12-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0006_project_screenshot_folder_project_upload_folder'),
        ('auto_ui', '0024_uielement_locator'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipagesteps',
            name='module_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='auto_user.projectmodule'),
        ),
    ]
