# Generated by Django 4.1.5 on 2024-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0025_uipagesteps_module_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uicasestepsdetailed',
            options={},
        ),
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='case_data',
            field=models.JSONField(null=True, verbose_name='用例步骤数据'),
        ),
    ]
