# Generated by Django 4.1.5 on 2024-01-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0026_alter_uicasestepsdetailed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='error_message',
            field=models.TextField(null=True, verbose_name='错误提示'),
        ),
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='status',
            field=models.SmallIntegerField(null=True, verbose_name='状态'),
        ),
    ]
