# Generated by Django 4.1.5 on 2024-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_ui', '0027_uicasestepsdetailed_error_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uieleresult',
            old_name='msg',
            new_name='error_message',
        ),
        migrations.AddField(
            model_name='uicase',
            name='test_suite_id',
            field=models.BigIntegerField(null=True, verbose_name='测试套件id'),
        ),
        migrations.AddField(
            model_name='uicaseresult',
            name='error_message',
            field=models.TextField(null=True, verbose_name='错误提示'),
        ),
        migrations.AddField(
            model_name='uicaseresult',
            name='is_batch',
            field=models.SmallIntegerField(null=True, verbose_name='是否是批量'),
        ),
        migrations.AddField(
            model_name='uipagestepsresult',
            name='error_message',
            field=models.TextField(null=True, verbose_name='错误提示'),
        ),
    ]
