# Generated by Django 4.1.5 on 2024-02-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0028_rename_msg_uieleresult_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicase',
            name='level',
            field=models.SmallIntegerField(null=True, verbose_name='用例级别'),
        ),
    ]
