# Generated by Django 4.1.5 on 2024-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0032_uicase_front_custom_uicase_front_sql_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipagestepsdetailed',
            name='key_list',
            field=models.JSONField(null=True, verbose_name='sql查询结果的key_list'),
        ),
        migrations.AddField(
            model_name='uipagestepsdetailed',
            name='sql',
            field=models.CharField(max_length=1048, null=True, verbose_name='sql'),
        ),
    ]
