# Generated by Django 5.0.3 on 2024-03-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0033_uipagestepsdetailed_key_list_uipagestepsdetailed_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uielement',
            name='loc',
            field=models.CharField(max_length=1048, null=True, verbose_name='元素定位'),
        ),
    ]
