# Generated by Django 5.0.3 on 2024-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0034_alter_uielement_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipagestepsdetailed',
            name='key',
            field=models.CharField(max_length=1048, null=True, verbose_name='key'),
        ),
        migrations.AddField(
            model_name='uipagestepsdetailed',
            name='value',
            field=models.CharField(max_length=1048, null=True, verbose_name='value'),
        ),
    ]
