# Generated by Django 4.1.5 on 2024-04-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0036_remove_uielement_locator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uicaseresult',
            name='is_batch',
        ),
    ]
