# Generated by Django 4.1.5 on 2025-02-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0001_initial'),
        ('auto_system', '0005_remove_tasks_type_remove_tasksdetails_case_id_and_more'),
        ('auto_ui', '0003_pagesteps_result_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiCaseSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='测试套件名称')),
                ('parametrize', models.JSONField(null=True, verbose_name='参数化')),
                ('status', models.SmallIntegerField(default=2, verbose_name='状态')),
                ('result_data', models.JSONField(null=True, verbose_name='最近一次执行结果')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uicase')),
                ('case_people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user', verbose_name='测试套件责任人')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.productmodule')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'ui_case_suite',
                'ordering': ['-id'],
            },
        ),
    ]
