# Generated by Django 4.1.5 on 2025-02-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0002_alter_user_config_alter_user_mailbox_and_more'),
        ('auto_system', '0004_remove_cachedata_case_id_remove_cachedata_case_type_and_more'),
        ('auto_ui', '0003_pagesteps_result_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicase',
            name='parametrize',
            field=models.JSONField(default=list, verbose_name='参数化'),
        ),
        migrations.AlterField(
            model_name='page',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.productmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=1048, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='pageelement',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_ui.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pageelement',
            name='sleep',
            field=models.SmallIntegerField(null=True, verbose_name='等待时间'),
        ),
        migrations.AlterField(
            model_name='pageelement',
            name='sub',
            field=models.SmallIntegerField(null=True, verbose_name='下标'),
        ),
        migrations.AlterField(
            model_name='pagesteps',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.productmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagesteps',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_ui.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagesteps',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagesteps',
            name='run_flow',
            field=models.TextField(null=True, verbose_name='步骤顺序'),
        ),
        migrations.AlterField(
            model_name='pagestepsdetailed',
            name='ele_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_ui.pageelement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagestepsdetailed',
            name='page_step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_ui.pagesteps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_flow',
            field=models.TextField(null=True, verbose_name='步骤顺序'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_people',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_user.user', verbose_name='用例责任人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uicase',
            name='front_custom',
            field=models.JSONField(default=list, verbose_name='前置自定义'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='front_sql',
            field=models.JSONField(default=list, verbose_name='前置sql'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='用例级别'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.productmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uicase',
            name='posterior_sql',
            field=models.JSONField(default=list, verbose_name='后置sql'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uicasestepsdetailed',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_ui.uicase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uicasestepsdetailed',
            name='case_sort',
            field=models.SmallIntegerField(verbose_name='用例排序'),
        ),
        migrations.AlterField(
            model_name='uicasestepsdetailed',
            name='page_step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_ui.pagesteps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uiconfig',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uipublic',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct'),
            preserve_default=False,
        ),
    ]
