# Generated by Django 4.1.5 on 2025-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0005_alter_pagestepsdetailed_ele_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicase',
            name='switch_step_open_url',
            field=models.SmallIntegerField(default=0, verbose_name='是否在切换步骤的时候切换url'),
        ),
    ]
