# Generated by Django 4.1.5 on 2025-05-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0006_uicase_switch_step_open_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uicase',
            name='switch_step_open_url',
        ),
        migrations.RemoveField(
            model_name='uicasestepsdetailed',
            name='case_cache_ass',
        ),
        migrations.RemoveField(
            model_name='uicasestepsdetailed',
            name='case_cache_data',
        ),
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='error_retry',
            field=models.SmallIntegerField(null=True, verbose_name='失败重试'),
        ),
        migrations.AddField(
            model_name='uicasestepsdetailed',
            name='switch_step_open_url',
            field=models.SmallIntegerField(default=0, verbose_name='是否在执行页面的时候切换url'),
        ),
    ]
