# Generated by Django 5.2.1 on 2025-06-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0007_remove_uicase_switch_step_open_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UiConfig',
        ),
    ]
