# Generated by Django 4.1.5 on 2025-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0009_pageelement_exp2_pageelement_exp3_pageelement_loc2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestepsdetailed',
            name='if_actual',
            field=models.CharField(max_length=1048, null=True, verbose_name='条件实际值'),
        ),
        migrations.AddField(
            model_name='pagestepsdetailed',
            name='if_failure',
            field=models.SmallIntegerField(null=True, verbose_name='条件不成立时'),
        ),
        migrations.AddField(
            model_name='pagestepsdetailed',
            name='if_pass',
            field=models.SmallIntegerField(null=True, verbose_name='条件成立时'),
        ),
        migrations.AlterField(
            model_name='pagestepsdetailed',
            name='ope_value',
            field=models.JSONField(null=True, verbose_name='操作输入值，也是条件预期值'),
        ),
    ]
