# Generated by Django 4.1.5 on 2025-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0009_pageelement_exp2_pageelement_exp3_pageelement_loc2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesteps',
            name='flow_data',
            field=models.JSONField(default=dict, verbose_name='flow_data'),
        ),
        migrations.AddField(
            model_name='pagestepsdetailed',
            name='condition_value',
            field=models.JSONField(null=True, verbose_name='条件判断'),
        ),
        migrations.AddField(
            model_name='pagestepsdetailed',
            name='func',
            field=models.TextField(null=True, verbose_name='func'),
        ),
    ]
