# Generated by Django 4.1.5 on 2025-09-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0010_pagesteps_flow_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageelement',
            name='sub2',
            field=models.SmallIntegerField(null=True, verbose_name='下标2'),
        ),
        migrations.AddField(
            model_name='pageelement',
            name='sub3',
            field=models.SmallIntegerField(null=True, verbose_name='下标3'),
        ),
    ]
