# Generated by Django 4.1.5 on 2025-09-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0010_pagestepsdetailed_if_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesteps',
            name='flow_data',
            field=models.JSONField(default=dict, verbose_name='flow_data'),
        ),
    ]
