# Generated by Django 4.1.5 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0011_pageelement_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesteps',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='level',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='用例级别'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=2, verbose_name='状态'),
        ),
    ]
