# Generated by Django 4.1.5 on 2025-09-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0011_pagesteps_flow_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagestepsdetailed',
            name='if_actual',
        ),
        migrations.RemoveField(
            model_name='pagestepsdetailed',
            name='if_failure',
        ),
        migrations.RemoveField(
            model_name='pagestepsdetailed',
            name='if_pass',
        ),
        migrations.RemoveField(
            model_name='pagestepsdetailed',
            name='step_sort',
        ),
    ]
