# Generated by Django 4.1.5 on 2026-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0013_uicase_scenario_description_uicase_scenario_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicase',
            name='scenario_layer',
            field=models.SmallIntegerField(default=0, verbose_name='场景层级'),
        ),
    ]
