# Generated by Django 4.1.5 on 2026-05-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0009_datafactorytemplate_usage_scope'),
        ('auto_ui', '0014_uicase_scenario_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipublic',
            name='datasource_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_data_factory.datafactorydatasourcealias', verbose_name='逻辑数据源'),
        ),
    ]
