# Generated by Django 4.1.5 on 2024-11-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('description', models.CharField(max_length=64, null=True, verbose_name='角色描述')),
            ],
            options={
                'db_table': 'role',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='昵称')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=64, verbose_name='登录密码')),
                ('ip', models.CharField(max_length=64, null=True, verbose_name='登录IP')),
                ('mailbox', models.JSONField(max_length=64, null=True, verbose_name='邮箱')),
                ('selected_project', models.SmallIntegerField(null=True, verbose_name='选中的项目ID')),
                ('selected_environment', models.SmallIntegerField(null=True, verbose_name='选中的环境ID')),
                ('last_login_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('config', models.JSONField(null=True, verbose_name='用户配置')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.role')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source_type', models.CharField(max_length=64, null=True, verbose_name='来源类型')),
                ('ip', models.CharField(max_length=64, null=True, verbose_name='登录IP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user')),
            ],
            options={
                'db_table': 'user_logs',
                'ordering': ['-create_time'],
            },
        ),
    ]
