# Generated by Django 4.1.5 on 2023-05-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目组名称')),
                ('status', models.SmallIntegerField(null=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('description', models.CharField(max_length=64, null=True, verbose_name='角色描述')),
            ],
            options={
                'db_table': 'role',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('username', models.CharField(max_length=64, verbose_name='登录账号')),
                ('password', models.CharField(max_length=64, verbose_name='登录密码')),
                ('ip', models.CharField(max_length=64, null=True, verbose_name='登录IP')),
                ('lastLoginTime', models.TimeField(null=True, verbose_name='上次登录时间')),
                ('department',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project')),
                ('role',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.role')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-id'],
            },
        ),
    ]
