# Generated by Django 4.1.5 on 2024-05-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('status', models.SmallIntegerField(null=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='产品名称')),
                ('type', models.SmallIntegerField(verbose_name='对应什么客户端')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project')),
            ],
            options={
                'db_table': 'project_product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('description', models.CharField(max_length=64, null=True, verbose_name='角色描述')),
            ],
            options={
                'db_table': 'role',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('username', models.CharField(max_length=64, null=True, verbose_name='登录账号')),
                ('source_type', models.CharField(max_length=64, null=True, verbose_name='来源类型')),
                ('ip', models.CharField(max_length=64, null=True, verbose_name='登录IP')),
                ('user_id', models.SmallIntegerField(null=True, verbose_name='选中的项目ID')),
            ],
            options={
                'db_table': 'user_logs',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('username', models.CharField(max_length=64, null=True, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='登录密码')),
                ('ip', models.CharField(max_length=64, null=True, verbose_name='登录IP')),
                ('last_login_time', models.DateTimeField(null=True, verbose_name='上次登录时间')),
                ('mailbox', models.CharField(max_length=64, null=True, verbose_name='邮箱')),
                ('selected_project', models.SmallIntegerField(null=True, verbose_name='选中的项目ID')),
                ('selected_environment', models.SmallIntegerField(null=True, verbose_name='选中的环境ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.role')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('environment', models.SmallIntegerField(verbose_name='环境备注')),
                ('name', models.CharField(max_length=64, verbose_name='被测试的对象')),
                ('value', models.CharField(max_length=1024, verbose_name='被测试的对象')),
                ('db_c_status', models.SmallIntegerField(null=True, verbose_name='查询权限')),
                ('db_rud_status', models.SmallIntegerField(null=True, verbose_name='增删改权限')),
                ('executor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.projectproduct')),
            ],
            options={
                'db_table': 'test_object',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='模块名称')),
                ('superior_module', models.CharField(max_length=64, null=True, verbose_name='上级模块名称')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.projectproduct')),
            ],
            options={
                'db_table': 'product_module',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('type', models.SmallIntegerField(null=True, verbose_name='类型')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='文件名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='文件大小')),
                ('file', models.FileField(null=True, upload_to='files/', verbose_name='文件')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.project')),
            ],
            options={
                'db_table': 'file_data',
            },
        ),
    ]
