# Generated by Django 4.1.5 on 2024-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='mailbox',
            field=models.JSONField(max_length=64, null=True, verbose_name='邮箱'),
        ),
    ]
