# Generated by Django 4.1.5 on 2023-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailbox',
            field=models.CharField(max_length=64, null=True, verbose_name='邮箱'),
        ),
    ]
