# Generated by Django 4.1.5 on 2023-11-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodule',
            old_name='module_name',
            new_name='name',
        ),
    ]
