# Generated by Django 4.1.5 on 2024-07-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0003_user_last_login_time_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproduct',
            name='type',
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='auto_type',
            field=models.SmallIntegerField(default=0, verbose_name='自动化类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='client_type',
            field=models.SmallIntegerField(default=0, verbose_name='客户端类型'),
            preserve_default=False,
        ),
    ]
