# Generated by Django 4.1.5 on 2023-11-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0003_remove_user_lastlogintime_user_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='superior_module',
            field=models.CharField(max_length=64, null=True, verbose_name='上级模块名称'),
        ),
    ]
