# Generated by Django 4.1.5 on 2024-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0004_remove_projectproduct_type_projectproduct_auto_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testobject',
            name='auto_type',
            field=models.SmallIntegerField(null=True, verbose_name='自动化使用类型'),
        ),
    ]
# Generated by Django 4.1.5 on 2024-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0004_remove_projectproduct_type_projectproduct_auto_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testobject',
            name='auto_type',
            field=models.SmallIntegerField(null=True, verbose_name='自动化使用类型'),
        ),
    ]
