# Generated by Django 4.1.5 on 2023-12-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0005_user_selected_environment_user_selected_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot_folder',
            field=models.CharField(max_length=64, null=True, verbose_name='执行失败的截图文件夹'),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_folder',
            field=models.CharField(max_length=64, null=True, verbose_name='上传文件存放的文件夹'),
        ),
    ]
