# Generated by Django 4.1.5 on 2024-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0005_testobject_auto_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='config',
            field=models.JSONField(null=True, verbose_name='用户配置'),
        ),
    ]
