# Generated by Django 4.1.5 on 2024-01-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0006_project_screenshot_folder_project_upload_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('username', models.CharField(max_length=64, null=True, verbose_name='登录账号')),
                ('ip', models.CharField(max_length=64, null=True, verbose_name='登录IP')),
                ('user_id', models.SmallIntegerField(null=True, verbose_name='选中的项目ID')),
            ],
            options={
                'db_table': 'user_logs',
                'ordering': ['id'],
            },
        ),
    ]
