# Generated by Django 4.1.5 on 2024-01-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0007_userlogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogs',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='userlogs',
            name='source_type',
            field=models.CharField(max_length=64, null=True, verbose_name='来源类型'),
        ),
    ]
