# Generated by Django 4.1.5 on 2025-02-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='config',
            field=models.JSONField(default=dict, verbose_name='用户配置'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mailbox',
            field=models.JSONField(default=list, max_length=64, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_user.user'),
            preserve_default=False,
        ),
    ]
