# Generated by Django 4.1.5 on 2025-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0002_alter_user_config_alter_user_mailbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='method',
            field=models.CharField(max_length=64, null=True, verbose_name='method'),
        ),
        migrations.AddField(
            model_name='userlogs',
            name='request_data',
            field=models.TextField(null=True, verbose_name='请求数据'),
        ),
        migrations.AddField(
            model_name='userlogs',
            name='response_data',
            field=models.TextField(null=True, verbose_name='响应数据'),
        ),
        migrations.AddField(
            model_name='userlogs',
            name='status_code',
            field=models.CharField(max_length=64, null=True, verbose_name='status_code'),
        ),
        migrations.AddField(
            model_name='userlogs',
            name='url',
            field=models.CharField(max_length=256, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='ip',
            field=models.CharField(max_length=64, null=True, verbose_name='IP'),
        ),
    ]
