# Generated by Codex on 2026-05-19

import secrets

from django.db import migrations, models


def generate_api_key() -> str:
    return f"mango_{secrets.token_urlsafe(32)}"


def fill_user_api_keys(apps, schema_editor):
    User = apps.get_model("auto_user", "User")
    used_keys = set(User.objects.exclude(api_key__isnull=True).values_list("api_key", flat=True))
    for user in User.objects.filter(api_key__isnull=True):
        api_key = generate_api_key()
        while api_key in used_keys or User.objects.filter(api_key=api_key).exists():
            api_key = generate_api_key()
        used_keys.add(api_key)
        user.api_key = api_key
        user.save(update_fields=["api_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("auto_user", "0003_userlogs_method_userlogs_request_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name="MCP APIKey"),
        ),
        migrations.RunPython(fill_user_api_keys, migrations.RunPython.noop),
    ]
