# Generated by Django 4.1.5 on 2025-02-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_system', '0005_remove_testsuite_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PytestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, null=True, verbose_name='目录名称')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'pytest_project',
            },
        ),
        migrations.CreateModel(
            name='PytestProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='模块目录名称')),
                ('pytest_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_pytest.pytestproject')),
            ],
            options={
                'db_table': 'pytest_module',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PytestInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, null=True, verbose_name='目录名称')),
                ('pytest_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_pytest.pytestproject')),
            ],
            options={
                'db_table': 'pytest_init',
            },
        ),
        migrations.CreateModel(
            name='PytestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, verbose_name='自定义用例名称')),
                ('file_name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('level', models.SmallIntegerField(default=1, verbose_name='用例级别')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('file_status', models.SmallIntegerField(default=0, verbose_name='文件状态')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_pytest.pytestprojectmodule')),
                ('pytest_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_pytest.pytestproject')),
            ],
            options={
                'db_table': 'pytest_case',
            },
        ),
        migrations.CreateModel(
            name='PytestAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, verbose_name='自定义ACT名称')),
                ('file_name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('file_status', models.SmallIntegerField(default=0, verbose_name='文件状态')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_pytest.pytestprojectmodule')),
                ('pytest_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_pytest.pytestproject')),
            ],
            options={
                'db_table': 'pytest_act',
            },
        ),
    ]
