# Generated by Django 4.1.5 on 2025-02-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytestact',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestprojectmodule'),
        ),
        migrations.AlterField(
            model_name='pytestact',
            name='pytest_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestproject'),
        ),
        migrations.AlterField(
            model_name='pytestcase',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestprojectmodule'),
        ),
        migrations.AlterField(
            model_name='pytestcase',
            name='pytest_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestproject'),
        ),
    ]
