# Generated by Django 4.1.5 on 2025-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytestprojectmodule',
            name='file_name',
            field=models.CharField(default=1, max_length=1024, verbose_name='文件名称'),
            preserve_default=False,
        ),
    ]
