# Generated by Django 4.1.5 on 2025-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0002_pytestprojectmodule_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytestproject',
            name='file_name',
            field=models.CharField(default=1, max_length=1024, verbose_name='文件名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pytestproject',
            name='name',
            field=models.CharField(max_length=1024, null=True, verbose_name='名称'),
        ),
    ]
