# Generated by Django 4.1.5 on 2025-03-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0003_rename_pytestproject_pytestproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytestact',
            name='project_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestproduct'),
        ),
        migrations.AlterField(
            model_name='pytestcase',
            name='project_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestproduct'),
        ),
        migrations.AlterField(
            model_name='pytesttestfile',
            name='project_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestproduct'),
        ),
        migrations.AlterField(
            model_name='pytesttools',
            name='project_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestproduct'),
        ),
    ]
