# Generated by Django 4.1.5 on 2025-08-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0004_alter_pytestact_project_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pytestact',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pytestcase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pytestproduct',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pytesttestfile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pytesttools',
            options={'ordering': ['-id']},
        ),
    ]
