# Generated by Django 4.1.5 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0005_alter_pytestact_options_alter_pytestcase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytestcase',
            name='level',
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name='用例级别'),
        ),
        migrations.AlterField(
            model_name='pytestcase',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='状态'),
        ),
    ]
