# Generated by Django 4.1.5 on 2026-05-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0006_alter_pytestcase_level_alter_pytestcase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytesttestfile',
            name='project_product',
        ),
        migrations.RemoveField(
            model_name='pytesttools',
            name='module',
        ),
        migrations.RemoveField(
            model_name='pytesttools',
            name='project_product',
        ),
        migrations.AddField(
            model_name='pytestproduct',
            name='test_dir',
            field=models.JSONField(default=list, verbose_name='测试目录名称'),
        ),
        migrations.DeleteModel(
            name='PytestAct',
        ),
        migrations.DeleteModel(
            name='PytestTestFile',
        ),
        migrations.DeleteModel(
            name='PytestTools',
        ),
    ]
