# Generated by Django 4.1.5 on 2026-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0007_remove_pytesttestfile_project_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytestcase',
            name='feature_file_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='feature文件路径'),
        ),
    ]
