# Generated by Django 4.1.5 on 2026-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0008_pytestcase_feature_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytestcase',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=2, verbose_name='状态'),
        ),
    ]
