# Generated by Django 4.1.5 on 2025-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0003_remove_filedata_file_remove_filedata_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproduct',
            name='client_type',
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='api_client_type',
            field=models.SmallIntegerField(default=1, verbose_name='API客户端类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='ui_client_type',
            field=models.SmallIntegerField(default=2, verbose_name='UI客户端类型'),
            preserve_default=False,
        ),
    ]
