# Generated by Django 4.1.5 on 2025-02-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0002_alter_user_config_alter_user_mailbox_and_more'),
        ('auto_api', '0002_remove_apicasedetailed_ass_response_value_and_more'),
        ('auto_ui', '0003_pagesteps_result_data'),
        ('auto_system', '0003_remove_filedata_file_remove_filedata_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedata',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='cachedata',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='projectproduct',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='command',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='update_time',
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='api_client_type',
            field=models.SmallIntegerField(default=0, verbose_name='API客户端类型'),
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='ui_client_type',
            field=models.SmallIntegerField(default=0, verbose_name='UI客户端类型'),
        ),
        migrations.AddField(
            model_name='tasksdetails',
            name='api_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicase'),
        ),
        migrations.AddField(
            model_name='tasksdetails',
            name='type',
            field=models.SmallIntegerField(default=0, verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='tasksdetails',
            name='ui_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uicase'),
        ),
        migrations.AlterField(
            model_name='cachedata',
            name='key',
            field=models.CharField(max_length=128, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='database',
            name='test_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.testobject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticeconfig',
            name='test_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.testobject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectproduct',
            name='auto_type',
            field=models.SmallIntegerField(default=0, verbose_name='自动化类型'),
        ),
        migrations.AlterField(
            model_name='projectproduct',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='case_people',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_user.user',
                                    verbose_name='用例责任人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='is_notice',
            field=models.SmallIntegerField(default=0, verbose_name='是否发送通知'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='test_env',
            field=models.SmallIntegerField(default=0, verbose_name='测试环境'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timing_strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.timetasks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksdetails',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.tasks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testobject',
            name='auto_type',
            field=models.SmallIntegerField(default=0, verbose_name='自动化使用类型'),
        ),
        migrations.AlterField(
            model_name='testobject',
            name='db_c_status',
            field=models.SmallIntegerField(default=0, verbose_name='查询权限'),
        ),
        migrations.AlterField(
            model_name='testobject',
            name='db_rud_status',
            field=models.SmallIntegerField(default=0, verbose_name='增删改权限'),
        ),
        migrations.AlterField(
            model_name='testobject',
            name='executor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testobject',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.tasks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_user.user',
                                    verbose_name='用例执行人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuitedetails',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuitedetails',
            name='test_suite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_system.testsuite'),
            preserve_default=False,
        ),
    ]
