# Generated by Django 4.1.5 on 2025-02-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0004_remove_cachedata_case_id_remove_cachedata_case_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='type',
        ),
    ]
