# Generated by Django 4.1.5 on 2025-02-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_ui', '0003_pagesteps_result_data'),
        ('auto_api', '0013_remove_apicasesuite_case_flow_and_more'),
        ('auto_system', '0004_remove_projectproduct_client_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='command',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='tasksdetails',
            name='update_time',
        ),
        migrations.AddField(
            model_name='tasksdetails',
            name='api_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicase'),
        ),
        migrations.AddField(
            model_name='tasksdetails',
            name='api_case_suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_api.apicasesuite'),
        ),
        migrations.AddField(
            model_name='tasksdetails',
            name='type',
            field=models.SmallIntegerField(default=1, verbose_name='任务类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksdetails',
            name='ui_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uicase'),
        ),
    ]
