# Generated by Django 4.1.5 on 2025-02-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0005_remove_testsuite_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproduct',
            name='auto_type',
        ),
    ]
