# Generated by Django 4.1.5 on 2025-02-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0005_remove_tasks_type_remove_tasksdetails_case_id_and_more'),
        ('auto_ui', '0004_uicasesuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksdetails',
            name='ui_case_suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_ui.uicasesuite'),
        ),
    ]
