# Generated by Django 4.1.5 on 2025-03-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pytest', '0003_rename_pytestproject_pytestproduct_and_more'),
        ('auto_system', '0007_alter_testsuite_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksdetails',
            name='pytest_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_pytest.pytestcase'),
        ),
        migrations.AlterField(
            model_name='testsuitedetails',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_system.testsuite'),
        ),
    ]
