# Generated by Django 4.1.5 on 2025-03-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0007_alter_testsuite_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitedetails',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_system.testsuite'),
        ),
    ]
