# Generated by Django 4.1.5 on 2025-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_system', '0008_tasksdetails_pytest_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuitedetails',
            name='parametrize',
            field=models.JSONField(default=list, verbose_name='参数化'),
        ),
    ]
