# Generated by Django 4.1.5 on 2025-12-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user', '0003_userlogs_method_userlogs_request_data_and_more'),
        ('auto_system', '0011_alter_projectproduct_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='通知组名称')),
                ('feishu', models.CharField(max_length=255, null=True, verbose_name='飞书通知')),
                ('dingding', models.CharField(max_length=255, null=True, verbose_name='钉钉通知')),
                ('work_weixin', models.CharField(max_length=255, null=True, verbose_name='企业微信通知')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.project')),
                ('users', models.ManyToManyField(blank=True, related_name='notice_groups', to='auto_user.user', verbose_name='邮件通知用户')),
            ],
            options={
                'db_table': 'notice_group',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='NoticeConfig',
        ),
        migrations.AddField(
            model_name='tasks',
            name='notice_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.noticegroup', verbose_name='通知组'),
        ),
    ]
