# Generated by Django 4.1.5 on 2025-12-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0012_noticegroup_delete_noticeconfig_tasks_notice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='project_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_system.projectproduct'),
        ),
    ]
