# Generated by Django 4.1.5 on 2026-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0015_alter_testsuite_is_notice_alter_testsuite_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testsuitedetails',
            index=models.Index(fields=['test_suite_id', 'type', 'status'], name='idx_suite_type_status'),
        ),
    ]
