# Generated by Django 4.1.5 on 2026-05-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0017_database_db_type'),
        ('auto_data_factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFactoryDatasourceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='逻辑数据源名称')),
                ('code', models.CharField(max_length=64, verbose_name='逻辑数据源编码')),
                ('db_type', models.SmallIntegerField(default=0, verbose_name='数据库类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], db_index=True, default=1, verbose_name='状态')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'data_factory_datasource_alias',
                'ordering': ['-id'],
                'unique_together': {('project_product', 'code')},
            },
        ),
        migrations.AddField(
            model_name='datafactoryexecutionitem',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_system.database'),
        ),
        migrations.AddField(
            model_name='datafactoryentity',
            name='datasource_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto_data_factory.datafactorydatasourcealias'),
        ),
        migrations.CreateModel(
            name='DataFactoryDatasourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭&失败'), (1, '启用&通过')], db_index=True, default=1, verbose_name='状态')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.database')),
                ('datasource_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_data_factory.datafactorydatasourcealias')),
                ('test_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.testobject')),
            ],
            options={
                'db_table': 'data_factory_datasource_binding',
                'ordering': ['-id'],
                'unique_together': {('datasource_alias', 'test_object')},
            },
        ),
    ]
