# Generated by Codex on 2026-05-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafactoryentity',
            name='database',
        ),
        migrations.RemoveField(
            model_name='datafactoryentity',
            name='source_mode',
        ),
        migrations.RemoveField(
            model_name='datafactoryentity',
            name='create_config',
        ),
        migrations.RemoveField(
            model_name='datafactoryentity',
            name='delete_config',
        ),
    ]
