# Generated by Codex on 2026-05-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0017_database_db_type'),
        ('auto_data_factory', '0002_remove_unused_entity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactoryentity',
            name='module',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='auto_system.productmodule',
            ),
        ),
        migrations.AddField(
            model_name='datafactorytemplate',
            name='module',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='auto_system.productmodule',
            ),
        ),
        migrations.AddField(
            model_name='datafactoryexecution',
            name='module',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='auto_system.productmodule',
            ),
        ),
    ]
