# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0002_remove_unused_entity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafactoryexecution',
            name='source_type',
            field=models.SmallIntegerField(
                choices=[
                    (1, '模板调试'),
                    (2, '手动执行'),
                    (3, '系统调用'),
                    (4, 'API用例'),
                ],
                default=1,
                verbose_name='执行来源',
            ),
        ),
    ]
