# Generated by Django 4.1.5 on 2026-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_system', '0017_database_db_type'),
        ('auto_data_factory', '0002_datafactorydatasourcealias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafactoryfield',
            name='generator_type',
            field=models.SmallIntegerField(choices=[(0, '跳过'), (1, '固定值'), (2, '随机字符串'), (3, '随机整数'), (4, '随机小数'), (5, '当前时间'), (6, '相对时间'), (7, 'UUID'), (8, '自动编号'), (9, '枚举值'), (10, '表达式'), (11, '依赖实体字段'), (12, 'SQL查询结果'), (13, '测试数据方法')], default=1, verbose_name='生成方式'),
        ),
        migrations.AlterUniqueTogether(
            name='datafactoryentity',
            unique_together={('project_product', 'datasource_alias', 'table_name')},
        ),
        migrations.AlterUniqueTogether(
            name='datafactorytemplate',
            unique_together={('entity', 'name')},
        ),
        migrations.RemoveField(
            model_name='datafactoryentity',
            name='code',
        ),
        migrations.RemoveField(
            model_name='datafactoryentity',
            name='default_alias',
        ),
        migrations.RemoveField(
            model_name='datafactorytemplate',
            name='code',
        ),
        migrations.RemoveField(
            model_name='datafactorytemplate',
            name='default_alias',
        ),
    ]
