# Generated by Django 4.1.5 on 2026-05-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0003_alter_datafactoryfield_generator_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafactoryfield',
            name='output_enabled',
        ),
        migrations.RemoveField(
            model_name='datafactoryfield',
            name='output_name',
        ),
    ]
