# Generated by Django 4.1.5 on 2026-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0004_datafactorytemplate_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactoryexecutionitem',
            name='cleanup_sql',
            field=models.TextField(blank=True, null=True, verbose_name='清理SQL'),
        ),
        migrations.AddField(
            model_name='datafactoryexecutionitem',
            name='cleanup_sql_params',
            field=models.JSONField(default=dict, verbose_name='清理SQL参数'),
        ),
        migrations.AddField(
            model_name='datafactoryexecutionitem',
            name='insert_data',
            field=models.JSONField(default=dict, verbose_name='插入数据'),
        ),
        migrations.AddField(
            model_name='datafactoryexecutionitem',
            name='insert_sql',
            field=models.TextField(blank=True, null=True, verbose_name='插入SQL'),
        ),
        migrations.AddField(
            model_name='datafactoryexecutionitem',
            name='insert_sql_params',
            field=models.JSONField(default=dict, verbose_name='插入SQL参数'),
        ),
        migrations.AddField(
            model_name='datafactorytemplate',
            name='config_status',
            field=models.SmallIntegerField(choices=[(0, '待完善'), (1, '已就绪')], db_index=True, default=0, verbose_name='配置状态'),
        ),
    ]
