# Generated by Django 4.1.5 on 2026-05-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0004_remove_datafactoryfield_output_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafactoryexecution',
            name='source_name',
        ),
    ]
