# Generated by Django 4.1.5 on 2026-05-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0004_datafactorycaseconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafactorycaseconfig',
            name='source_type',
            field=models.SmallIntegerField(choices=[(1, 'API用例'), (2, 'UI用例'), (3, 'API接口场景')], db_index=True, verbose_name='用例类型'),
        ),
        migrations.AlterField(
            model_name='datafactoryexecution',
            name='source_type',
            field=models.SmallIntegerField(choices=[(1, '模板调试'), (2, '手动执行'), (3, '系统调用'), (4, 'API用例'), (5, 'API接口场景')], default=1, verbose_name='执行来源'),
        ),
    ]
