# Generated by Django 4.1.5 on 2026-05-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0005_remove_datafactoryexecution_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafactoryexecutionitem',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='datafactoryexecutionitem',
            name='unique_value',
        ),
    ]
