# Generated by Django 4.1.5 on 2026-05-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0005_datafactoryexecutionitem_cleanup_sql_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFactoryTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='关联名称')),
                ('sort', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('field_overrides', models.JSONField(default=dict, verbose_name='字段覆盖')),
                ('cleanup_strategy', models.SmallIntegerField(blank=True, null=True, verbose_name='清理策略覆盖')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('child_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_template_items', to='auto_data_factory.datafactorytemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auto_data_factory.datafactorytemplate')),
            ],
            options={
                'db_table': 'data_factory_template_item',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
