# Generated by Codex on 2026-05-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_data_factory', '0006_remove_datafactoryexecutionitem_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafactoryentity',
            name='cleanup_strategy',
        ),
    ]
