# Generated by Django 4.1.5 on 2025-02-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auto_system', '0006_remove_projectproduct_auto_type'),
        ('auto_user', '0002_alter_user_config_alter_user_mailbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PytestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, null=True, verbose_name='名称')),
                ('file_name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('init_file', models.CharField(max_length=1024, null=True, verbose_name='__init__文件')),
                ('auto_type', models.SmallIntegerField(default=0, verbose_name='自动化类型')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                      to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'pytest_project',
            },
        ),
        migrations.CreateModel(
            name='PytestProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='模块目录名称')),
                ('file_name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('pytest_project',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_pytest.pytestproject')),
            ],
            options={
                'db_table': 'pytest_module',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PytestTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, verbose_name='自定义用例名称')),
                ('file_name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('file_path', models.CharField(max_length=1024, verbose_name='文件路径')),
                ('file_status', models.SmallIntegerField(default=0, verbose_name='文件状态')),
                ('file_update_time', models.DateTimeField(verbose_name='文档修改时间')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='auto_pytest.pytestprojectmodule')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                      to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'pytest_tools',
            },
        ),
        migrations.CreateModel(
            name='PytestTestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('file_name', models.CharField(max_length=1024, verbose_name='带目录的文件名称')),
                ('file_path', models.CharField(max_length=1024, verbose_name='文件路径')),
                ('file_update_time', models.DateTimeField(verbose_name='文档修改时间')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='auto_pytest.pytestprojectmodule')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                      to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'pytest_test_file',
            },
        ),
        migrations.CreateModel(
            name='PytestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, verbose_name='自定义用例名称')),
                ('level', models.SmallIntegerField(default=1, verbose_name='用例级别')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('file_name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('file_path', models.CharField(max_length=1024, verbose_name='文件路径')),
                ('file_status', models.SmallIntegerField(default=0, verbose_name='文件状态')),
                ('file_update_time', models.DateTimeField(verbose_name='文档修改时间')),
                ('result_data', models.JSONField(null=True, verbose_name='最新一次测试结果')),
                ('case_people',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_user.user',
                                   verbose_name='用例责任人')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='auto_pytest.pytestprojectmodule')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                      to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'pytest_case',
            },
        ),
        migrations.CreateModel(
            name='PytestAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=1024, verbose_name='自定义ACT名称')),
                ('file_name', models.CharField(max_length=1024, verbose_name='文件名称')),
                ('file_path', models.CharField(max_length=1024, verbose_name='文件路径')),
                ('file_status', models.SmallIntegerField(default=0, verbose_name='文件状态')),
                ('file_update_time', models.DateTimeField(verbose_name='文档修改时间')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='auto_pytest.pytestprojectmodule')),
                ('project_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                      to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'pytest_act',
            },
        ),
    ]
