# Generated by Django 4.1.5 on 2025-02-25 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auto_pytest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytesttestfile',
            name='module',
        ),
    ]
