# Generated by Django 4.1.5 on 2026-06-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_system', '0019_testsuitedetailresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('task_name', models.CharField(max_length=128, null=True, verbose_name='任务名称快照')),
                ('fire_key', models.CharField(max_length=191, null=True, unique=True, verbose_name='触发唯一键')),
                ('planned_at', models.DateTimeField(db_index=True, verbose_name='计划触发时间')),
                ('fired_at', models.DateTimeField(null=True, verbose_name='实际触发时间')),
                ('source_type', models.SmallIntegerField(choices=[(0, '测试套执行'), (1, 'Token刷新'), (2, '数据清理'), (3, '监控任务'), (4, '系统任务')], db_index=True, default=0, verbose_name='触发类型')),
                ('status', models.SmallIntegerField(choices=[(0, '待分发'), (1, '分发中'), (2, '已分发'), (3, '成功'), (4, '失败'), (5, '已跳过'), (6, '已取消')], db_index=True, default=0, verbose_name='状态')),
                ('trigger_node', models.CharField(max_length=128, null=True, verbose_name='触发节点')),
                ('dispatcher_node', models.CharField(max_length=128, null=True, verbose_name='分发节点')),
                ('error_message', models.TextField(null=True, verbose_name='错误信息')),
                ('extra_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.tasks', verbose_name='定时任务')),
                ('test_suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.testsuite', verbose_name='测试套')),
                ('time_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_system.timetasks', verbose_name='定时策略')),
            ],
            options={
                'db_table': 'schedule_fire',
                'ordering': ['-planned_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='schedulefire',
            index=models.Index(fields=['status', 'planned_at'], name='idx_fire_status_plan'),
        ),
        migrations.AddIndex(
            model_name='schedulefire',
            index=models.Index(fields=['task', 'planned_at'], name='idx_fire_task_plan'),
        ),
        migrations.AddConstraint(
            model_name='schedulefire',
            constraint=models.UniqueConstraint(fields=('time_task', 'task', 'planned_at', 'source_type'), name='uniq_schedule_fire_task_plan_type'),
        ),
    ]
