# Generated by Django 4.1.5 on 2025-02-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auto_user', '0002_alter_user_config_alter_user_mailbox_and_more'),
        ('auto_system', '0003_remove_filedata_file_remove_filedata_price_and_more'),
        ('auto_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='ass_response_value',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='ass_response_whole',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='ass_sql',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='data',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='file',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='front_sql',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='header',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='json',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='params',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='posterior_response',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='posterior_sleep',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='posterior_sql',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='apicasedetailed',
            name='url',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='front_custom',
        ),
        migrations.RemoveField(
            model_name='apipublic',
            name='client',
        ),
        migrations.AddField(
            model_name='apicase',
            name='parametrize',
            field=models.JSONField(default=list, verbose_name='参数化'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='posterior_func',
            field=models.TextField(null=True, verbose_name='后置自定义'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='posterior_json_path',
            field=models.JSONField(default=list, verbose_name='后置jsonpath提取'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='posterior_re',
            field=models.JSONField(default=list, verbose_name='后置正则提取'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='result_data',
            field=models.JSONField(null=True, verbose_name='最近一次执行结果'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='case_people',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_user.user',
                                    verbose_name='用例责任人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apicase',
            name='front_custom',
            field=models.JSONField(default=list, verbose_name='前置方法'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='front_headers',
            field=models.JSONField(default=list, verbose_name='前置请求头'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='front_sql',
            field=models.JSONField(default=list, verbose_name='前置sql'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='用例级别'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.productmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apicase',
            name='posterior_sql',
            field=models.JSONField(default=list, verbose_name='后置sql'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apicasedetailed',
            name='api_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_api.apiinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apicasedetailed',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto_api.apicase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='header',
            field=models.JSONField(null=True, verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.productmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apipublic',
            name='project_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='auto_system.projectproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apipublic',
            name='type',
            field=models.SmallIntegerField(default=0, verbose_name='自定义变量类型'),
        ),
        migrations.AlterField(
            model_name='apipublic',
            name='value',
            field=models.TextField(verbose_name='值'),
        ),
        migrations.CreateModel(
            name='ApiHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('key', models.CharField(max_length=128, verbose_name='键')),
                ('value', models.TextField(verbose_name='值')),
                ('status', models.SmallIntegerField(default=0, verbose_name='是否默认开启')),
                ('project_product',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_system.projectproduct')),
            ],
            options={
                'db_table': 'api_headers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApiCaseDetailedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128, verbose_name='步骤名称')),
                ('header', models.JSONField(default=list, verbose_name='请求头')),
                ('params', models.JSONField(null=True, verbose_name='参数')),
                ('data', models.JSONField(null=True, verbose_name='data')),
                ('json', models.JSONField(null=True, verbose_name='json')),
                ('file', models.JSONField(null=True, verbose_name='file')),
                ('front_sql', models.JSONField(default=list, verbose_name='前置sql')),
                ('front_func', models.TextField(null=True, verbose_name='后置自定义')),
                ('ass_sql', models.JSONField(default=list, verbose_name='sql断言')),
                ('ass_json_all', models.JSONField(null=True, verbose_name='响应JSON全匹配断言')),
                ('ass_text_all', models.TextField(null=True, verbose_name='响应文本全匹配断言')),
                ('ass_jsonpath', models.JSONField(default=list, verbose_name='响应jsonpath断言')),
                ('posterior_sql', models.JSONField(default=list, verbose_name='后置sql')),
                ('posterior_response', models.JSONField(default=list, verbose_name='后置响应处理')),
                ('posterior_sleep', models.SmallIntegerField(null=True, verbose_name='强制等待')),
                ('posterior_func', models.TextField(null=True, verbose_name='后置自定义')),
                ('status', models.SmallIntegerField(default=2, verbose_name='状态')),
                ('result_data', models.JSONField(null=True, verbose_name='最近一次执行结果')),
                ('case_detailed',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_api.apicasedetailed')),
            ],
            options={
                'db_table': 'api_case_detailed_parameter',
            },
        ),
    ]
