# Generated by Django 4.1.5 on 2025-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0006_apicasedetailedparameter_ass_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='is_case_headers',
            field=models.SmallIntegerField(default=1, verbose_name='是否使用用例headers'),
        ),
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='posterior_file',
            field=models.JSONField(default=dict, verbose_name='文件下载'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='is_text_data',
            field=models.SmallIntegerField(default=1, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='is_text_json',
            field=models.SmallIntegerField(default=1, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='is_text_params',
            field=models.SmallIntegerField(default=1, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='posterior_file',
            field=models.CharField(max_length=1024, null=True, verbose_name='下载文件名称key'),
        ),
    ]
