# Generated by Django 4.1.5 on 2025-12-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0007_apicasedetailedparameter_is_case_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailed',
            name='error_message',
            field=models.TextField(null=True, verbose_name='失败提示'),
        ),
    ]
