# Generated by Django 4.1.5 on 2026-02-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0008_apicasedetailed_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicasedetailedparameter',
            name='posterior_response_text',
            field=models.JSONField(default=list, verbose_name='后置响应文本处理'),
        ),
    ]
