# Generated by Django 4.1.5 on 2026-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0012_apicasedetailedparameter_ass_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipublic',
            name='test_env',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='测试环境'),
        ),
    ]
