# Generated by Django 4.1.5 on 2026-05-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0013_apipublic_test_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='scenario_description',
            field=models.TextField(blank=True, null=True, verbose_name='场景描述'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='scenario_tags',
            field=models.JSONField(default=list, verbose_name='场景标签'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='scenario_type',
            field=models.SmallIntegerField(default=0, verbose_name='场景类型'),
        ),
    ]
