# Generated by Django 4.1.5 on 2026-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0018_apipublic_datasource_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthconfig',
            name='refresh_mode',
            field=models.SmallIntegerField(choices=[(0, '执行时检测刷新'), (1, '定时刷新'), (2, '执行时检测+定时刷新'), (3, '手动刷新')], db_index=True, default=0, verbose_name='刷新方式'),
        ),
    ]
