import { reactive } from 'vue'

export const uiColumns: any = reactive([
  {
    title: '用例ID',
    dataIndex: '__caseId',
    key: '__caseId',
    width: 78,
    align: 'center',
    mergeCell: true,
  },
  {
    title: '用例名称',
    dataIndex: '__caseName',
    key: '__caseName',
    width: 150,
    align: 'left',
    ellipsis: true,
    tooltip: true,
    mergeCell: true,
  },
  {
    title: '数量',
    dataIndex: '__caseCount',
    key: '__caseCount',
    width: 92,
    align: 'center',
    mergeCell: true,
  },
  {
    title: '步骤ID',
    dataIndex: 'id',
    key: 'id',
    width: 82,
  },
  {
    title: '步骤名称',
    dataIndex: 'name',
    key: 'name',
    align: 'left',
    width: 150,
    ellipsis: true,
    tooltip: true,
  },
  {
    title: '开始时间',
    dataIndex: 'test_time',
    key: 'test_time',
    width: 180,
  },
  {
    title: '结束时间',
    dataIndex: 'stop_time',
    key: 'stop_time',
    width: 180,
  },
  {
    title: '测试环境',
    dataIndex: 'test_object',
    key: 'test_object',
    align: 'left',
    width: 160,
    ellipsis: true,
    tooltip: true,
  },
  {
    title: '测试结果',
    dataIndex: 'status',
    key: 'status',
    width: 94,
  },
  {
    title: '失败提示',
    dataIndex: 'error_message',
    key: 'error_message',
    align: 'left',
    width: 260,
    ellipsis: true,
    tooltip: true,
  },
  {
    title: '操作',
    dataIndex: 'actions',
    key: 'actions',
    align: 'center',
    width: 170,
    fixed: 'right',
  },
])

export const apiColumns: any = reactive([
  {
    title: '用例ID',
    dataIndex: '__caseId',
    key: '__caseId',
    width: 78,
    align: 'center',
    mergeCell: true,
  },
  {
    title: '用例名称',
    dataIndex: '__caseName',
    key: '__caseName',
    align: 'left',
    width: 200,
    ellipsis: true,
    tooltip: true,
    mergeCell: true,
  },
  {
    title: '接口名称',
    dataIndex: '__apiInfoName',
    key: '__apiInfoName',
    align: 'left',
    width: 140,
    ellipsis: true,
    tooltip: true,
    mergeCell: true,
  },
  {
    title: '数量',
    dataIndex: '__caseCount',
    key: '__caseCount',
    width: 70,
    align: 'center',
    mergeCell: true,
  },
  {
    title: '场景名称',
    dataIndex: 'name',
    key: 'name',
    align: 'left',
    width: 400,
    ellipsis: true,
    tooltip: true,
  },
  {
    title: '开始时间',
    dataIndex: 'test_time',
    key: 'test_time',
    width: 180,
  },
  {
    title: '响应时间',
    dataIndex: 'response_time',
    key: 'response_time',
    width: 180,
  },
  {
    title: '测试结果',
    key: 'status',
    dataIndex: 'status',
    width: 94,
  },
  {
    title: '失败提示',
    dataIndex: 'error_message',
    key: 'error_message',
    align: 'left',
    width: 360,
    ellipsis: true,
    tooltip: true,
  },
  {
    title: '操作',
    dataIndex: 'actions',
    key: 'actions',
    align: 'center',
    width: 170,
    fixed: 'right',
  },
])
export const pytestColumns: any = reactive([
  {
    title: '用例ID',
    dataIndex: '__caseId',
    key: '__caseId',
    width: 78,
    align: 'center',
    mergeCell: true,
  },
  {
    title: '用例名称',
    dataIndex: '__caseName',
    key: '__caseName',
    width: 150,
    align: 'left',
    ellipsis: true,
    tooltip: true,
    mergeCell: true,
  },
  {
    title: '数量',
    dataIndex: '__caseCount',
    key: '__caseCount',
    width: 92,
    align: 'center',
    mergeCell: true,
  },
  {
    title: '用例名称',
    dataIndex: 'name',
    key: 'name',
    align: 'left',
    width: 150,
    ellipsis: true,
    tooltip: true,
  },
  {
    title: '开始时间',
    dataIndex: 'start',
    key: 'start',
    width: 180,
  },
  {
    title: '结束时间',
    dataIndex: 'stop',
    key: 'stop',
    width: 180,
  },
  {
    title: '测试结果',
    key: 'status',
    dataIndex: 'status',
    width: 94,
  },
  {
    title: '失败提示',
    dataIndex: 'error_message',
    key: 'error_message',
    align: 'left',
    width: 260,
    ellipsis: true,
    tooltip: true,
  },
  {
    title: '操作',
    dataIndex: 'actions',
    key: 'actions',
    align: 'center',
    width: 170,
    fixed: 'right',
  },
])
